# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import wakapi_unofficial_sdk.types as _response_types
from wakapi_unofficial_sdk.client import (
    ClientConfig,
    RequestOptions,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
)
from wakapi_unofficial_sdk.types import V1StatusBarViewModel, V1UserAgentsViewModel
from wakapi_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_wakatime_useragents(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1UserAgentsViewModel:
    """Lists the unique user agents recorded for a specified user. Use the `user` path
    parameter to select the user whose agent history you want to inspect.

    Mimics https://wakatime.com/developers#user_agents

    Args:
        user: User ID to fetch data for (or 'current')
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/user_agents",
        operation_id="get_wakatime_useragents",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1UserAgentsViewModel"), V1UserAgentsViewModel
    )


def get_wakatime_useragents_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1UserAgentsViewModel:
    """Lists the unique user agents recorded for a specified user. Use the `user` path
    parameter to select the user whose agent history you want to inspect.

    Mimics https://wakatime.com/developers#user_agents

    Args:
        user: User ID to fetch data for (or 'current')
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/user_agents",
        operation_id="get_wakatime_useragents",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1UserAgentsViewModel"), V1UserAgentsViewModel
    )


async def statusbar(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1StatusBarViewModel:
    """Retrieves today's activity summary for a specified user in a status-bar-compatible
    format. Use the `user` path parameter to select the user whose current-day activity
    you want to view.

    Mimics https://wakatime.com/api/v1/users/current/statusbar/today. Have no official
    documentation

    Args:
        user: User ID to fetch data for (or 'current')
    """

    _resp = await sdk_request(
        "GET",
        f"/users/{encode_path_segment(user)}/statusbar/today",
        operation_id="statusbar",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1StatusBarViewModel"), V1StatusBarViewModel
    )


def statusbar_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1StatusBarViewModel:
    """Retrieves today's activity summary for a specified user in a status-bar-compatible
    format. Use the `user` path parameter to select the user whose current-day activity
    you want to view.

    Mimics https://wakatime.com/api/v1/users/current/statusbar/today. Have no official
    documentation

    Args:
        user: User ID to fetch data for (or 'current')
    """

    _resp = sdk_request_sync(
        "GET",
        f"/users/{encode_path_segment(user)}/statusbar/today",
        operation_id="statusbar",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1StatusBarViewModel"), V1StatusBarViewModel
    )


__all__ = [
    "get_wakatime_useragents",
    "get_wakatime_useragents_sync",
    "statusbar",
    "statusbar_sync",
]
