# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import wakapi_unofficial_sdk.types as _response_types
from wakapi_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from wakapi_unofficial_sdk.types import (
    V1AllTimeViewModel,
    V1LeadersViewModel,
    V1ProjectsViewModel,
    V1ProjectViewModel,
    V1StatsViewModel,
    V1SummariesViewModel,
    V1UserViewModel,
)
from wakapi_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_wakatime_leaders(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> V1LeadersViewModel:
    """Lists users ranked by coding activity in descending order. Use this endpoint to
    retrieve the leaderboard, including its ranking data, current-user information, and
    range metadata.

    Mimics https://wakatime.com/developers#leaders
    """

    _resp = await sdk_request(
        "GET",
        "/compat/wakatime/v1/leaders",
        operation_id="get_wakatime_leaders",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1LeadersViewModel"), V1LeadersViewModel
    )


def get_wakatime_leaders_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> V1LeadersViewModel:
    """Lists users ranked by coding activity in descending order. Use this endpoint to
    retrieve the leaderboard, including its ranking data, current-user information, and
    range metadata.

    Mimics https://wakatime.com/developers#leaders
    """

    _resp = sdk_request_sync(
        "GET",
        "/compat/wakatime/v1/leaders",
        operation_id="get_wakatime_leaders",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1LeadersViewModel"), V1LeadersViewModel
    )


async def get_wakatime_user(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1UserViewModel:
    """Retrieves a user's profile information. Set `user` to a user ID or `current` to
    retrieve the profile associated with the authenticated user.

    Mimics https://wakatime.com/developers#users

    Args:
        user: User ID to fetch (or 'current')
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}",
        operation_id="get_wakatime_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1UserViewModel"), V1UserViewModel
    )


def get_wakatime_user_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1UserViewModel:
    """Retrieves a user's profile information. Set `user` to a user ID or `current` to
    retrieve the profile associated with the authenticated user.

    Mimics https://wakatime.com/developers#users

    Args:
        user: User ID to fetch (or 'current')
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}",
        operation_id="get_wakatime_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1UserViewModel"), V1UserViewModel
    )


async def get_all_time(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1AllTimeViewModel:
    """Retrieves a user's coding-time summary for all time since today. Set `user` to a
    user ID or `current` to select the user whose summary you want.

    Mimics https://wakatime.com/developers#all_time_since_today

    Args:
        user: User ID to fetch data for (or 'current')
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/all_time_since_today",
        operation_id="get_all_time",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1AllTimeViewModel"), V1AllTimeViewModel
    )


def get_all_time_sync(
    _client_config: ClientConfig,
    user: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1AllTimeViewModel:
    """Retrieves a user's coding-time summary for all time since today. Set `user` to a
    user ID or `current` to select the user whose summary you want.

    Mimics https://wakatime.com/developers#all_time_since_today

    Args:
        user: User ID to fetch data for (or 'current')
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/all_time_since_today",
        operation_id="get_all_time",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1AllTimeViewModel"), V1AllTimeViewModel
    )


async def get_wakatime_projects(
    _client_config: ClientConfig,
    user: str,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> V1ProjectsViewModel:
    """Lists a user's projects. Set `user` to a user ID or `current`, and optionally use
    `q` to filter the projects.

    Mimics https://wakatime.com/developers#projects

    Args:
        user: User ID to fetch data for (or 'current')
        q: Query to filter projects by
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/projects",
        params=serialize_query([("q", q, "form", True)]),
        operation_id="get_wakatime_projects",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1ProjectsViewModel"), V1ProjectsViewModel
    )


def get_wakatime_projects_sync(
    _client_config: ClientConfig,
    user: str,
    q: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> V1ProjectsViewModel:
    """Lists a user's projects. Set `user` to a user ID or `current`, and optionally use
    `q` to filter the projects.

    Mimics https://wakatime.com/developers#projects

    Args:
        user: User ID to fetch data for (or 'current')
        q: Query to filter projects by
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/projects",
        params=serialize_query([("q", q, "form", True)]),
        operation_id="get_wakatime_projects",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1ProjectsViewModel"), V1ProjectsViewModel
    )


async def get_wakatime_project(
    _client_config: ClientConfig,
    user: str,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1ProjectViewModel:
    """Retrieves a single project for a specified user. Provide `user` to select the user
    and `id` to identify the project.

    Mimics undocumented endpoint related to https://wakatime.com/developers#projects

    Args:
        user: User ID to fetch data for (or 'current')
        id: Project ID to fetch
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/projects/{encode_path_segment(id)}",
        operation_id="get_wakatime_project",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1ProjectViewModel"), V1ProjectViewModel
    )


def get_wakatime_project_sync(
    _client_config: ClientConfig,
    user: str,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1ProjectViewModel:
    """Retrieves a single project for a specified user. Provide `user` to select the user
    and `id` to identify the project.

    Mimics undocumented endpoint related to https://wakatime.com/developers#projects

    Args:
        user: User ID to fetch data for (or 'current')
        id: Project ID to fetch
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/projects/{encode_path_segment(id)}",
        operation_id="get_wakatime_project",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1ProjectViewModel"), V1ProjectViewModel
    )


async def get_wakatimes_tats(
    _client_config: ClientConfig,
    user: str,
    range: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str
    | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    label: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> V1StatsViewModel:
    """Retrieves coding-activity statistics for a user over a selected interval. Use the
    optional query parameters to filter the statistics by project, language, editor,
    operating system, machine, or project label.

    Mimics https://wakatime.com/developers#stats

    Args:
        user: User ID to fetch data for (or 'current')
        range: Range interval identifier
        project: Project to filter by
        language: Language to filter by
        editor: Editor to filter by
        operating_system: OS to filter by
        machine: Machine to filter by
        label: Project label to filter by
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/stats/{encode_path_segment(range)}",
        params=serialize_query(
            [
                ("project", project, "form", True),
                ("language", language, "form", True),
                ("editor", editor, "form", True),
                ("operating_system", operating_system, "form", True),
                ("machine", machine, "form", True),
                ("label", label, "form", True),
            ]
        ),
        operation_id="get_wakatimes_tats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1StatsViewModel"), V1StatsViewModel
    )


def get_wakatimes_tats_sync(
    _client_config: ClientConfig,
    user: str,
    range: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str
    | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    label: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> V1StatsViewModel:
    """Retrieves coding-activity statistics for a user over a selected interval. Use the
    optional query parameters to filter the statistics by project, language, editor,
    operating system, machine, or project label.

    Mimics https://wakatime.com/developers#stats

    Args:
        user: User ID to fetch data for (or 'current')
        range: Range interval identifier
        project: Project to filter by
        language: Language to filter by
        editor: Editor to filter by
        operating_system: OS to filter by
        machine: Machine to filter by
        label: Project label to filter by
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/stats/{encode_path_segment(range)}",
        params=serialize_query(
            [
                ("project", project, "form", True),
                ("language", language, "form", True),
                ("editor", editor, "form", True),
                ("operating_system", operating_system, "form", True),
                ("machine", machine, "form", True),
                ("label", label, "form", True),
            ]
        ),
        operation_id="get_wakatimes_tats",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1StatsViewModel"), V1StatsViewModel
    )


async def get_wakatime_summaries(
    _client_config: ClientConfig,
    user: str,
    range: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str
    | NotGiven = NOT_GIVEN,
    start: str | NotGiven = NOT_GIVEN,
    end: str | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    label: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> V1SummariesViewModel:
    """Retrieves WakaTime-compatible summaries for a specified user. Use `range` or the
    `start` and `end` dates to select a period, and apply project, language, editor,
    operating system, machine, or label filters to narrow the results.

    Mimics https://wakatime.com/developers#summaries.

    Args:
        user: User ID to fetch data for (or 'current')
        range: Range interval identifier
        start: Start date (e.g. '2021-02-07')
        end: End date (e.g. '2021-02-08')
        project: Project to filter by
        language: Language to filter by
        editor: Editor to filter by
        operating_system: OS to filter by
        machine: Machine to filter by
        label: Project label to filter by
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/summaries",
        params=serialize_query(
            [
                ("range", range, "form", True),
                ("start", start, "form", True),
                ("end", end, "form", True),
                ("project", project, "form", True),
                ("language", language, "form", True),
                ("editor", editor, "form", True),
                ("operating_system", operating_system, "form", True),
                ("machine", machine, "form", True),
                ("label", label, "form", True),
            ]
        ),
        operation_id="get_wakatime_summaries",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1SummariesViewModel"), V1SummariesViewModel
    )


def get_wakatime_summaries_sync(
    _client_config: ClientConfig,
    user: str,
    range: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str
    | NotGiven = NOT_GIVEN,
    start: str | NotGiven = NOT_GIVEN,
    end: str | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    label: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> V1SummariesViewModel:
    """Retrieves WakaTime-compatible summaries for a specified user. Use `range` or the
    `start` and `end` dates to select a period, and apply project, language, editor,
    operating system, machine, or label filters to narrow the results.

    Mimics https://wakatime.com/developers#summaries.

    Args:
        user: User ID to fetch data for (or 'current')
        range: Range interval identifier
        start: Start date (e.g. '2021-02-07')
        end: End date (e.g. '2021-02-08')
        project: Project to filter by
        language: Language to filter by
        editor: Editor to filter by
        operating_system: OS to filter by
        machine: Machine to filter by
        label: Project label to filter by
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/wakatime/v1/users/{encode_path_segment(user)}/summaries",
        params=serialize_query(
            [
                ("range", range, "form", True),
                ("start", start, "form", True),
                ("end", end, "form", True),
                ("project", project, "form", True),
                ("language", language, "form", True),
                ("editor", editor, "form", True),
                ("operating_system", operating_system, "form", True),
                ("machine", machine, "form", True),
                ("label", label, "form", True),
            ]
        ),
        operation_id="get_wakatime_summaries",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1SummariesViewModel"), V1SummariesViewModel
    )


__all__ = [
    "get_all_time",
    "get_all_time_sync",
    "get_wakatime_leaders",
    "get_wakatime_leaders_sync",
    "get_wakatime_project",
    "get_wakatime_project_sync",
    "get_wakatime_projects",
    "get_wakatime_projects_sync",
    "get_wakatime_summaries",
    "get_wakatime_summaries_sync",
    "get_wakatime_user",
    "get_wakatime_user_sync",
    "get_wakatimes_tats",
    "get_wakatimes_tats_sync",
]
