# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import httpx
import pytest

from wakapi_unofficial_sdk.client import (
    ClientConfig,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)


def test_path_and_query_serialization() -> None:
    assert encode_path_segment("/ ?#%雪") == "%2F%20%3F%23%25%E9%9B%AA"
    query = serialize_query(
        [
            ("repeated", ["a", "雪"], "form", True),
            ("csv", ["a", "b"], "form", False),
        ]
    )
    assert query == {"repeated": ["a", "雪"], "csv": "a,b"}


def test_sync_request_executes_transport() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.params.get_list("item") == ["a", "雪"]
        return httpx.Response(200, json={"ok": True}, headers={"x-request-id": "sync-id"})

    config = ClientConfig(base_url="https://example.test")
    config._sync_client = httpx.Client(transport=httpx.MockTransport(handler))
    try:
        response = sdk_request_sync("GET", "/probe", params={"item": ["a", "雪"]}, config=config)
        assert response.data == {"ok": True}
        assert response.request_id == "sync-id"
    finally:
        config.close()


@pytest.mark.asyncio
async def test_async_request_executes_transport() -> None:
    async def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/probe"
        return httpx.Response(
            200, content=b"raw", headers={"content-type": "application/octet-stream"}
        )

    config = ClientConfig(base_url="https://example.test")
    config._client = httpx.AsyncClient(transport=httpx.MockTransport(handler))
    try:
        response = await sdk_request("GET", "/probe", config=config, response_decoder="bytes")
        assert response.data == b"raw"
    finally:
        await config.aclose()
