# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import json
import pathlib
from typing import Any

import httpx
import pytest

from wakapi_unofficial_sdk.client import (
    ClientAuthConfig,
    ClientConfig,
    IdempotencyConfig,
    RetryConfig,
    encode_path_segment,
    sdk_request_sync,
    serialize_query,
)
from wakapi_unofficial_sdk.errors import SdkHttpError

FIXTURE = json.loads(
    (pathlib.Path(__file__).resolve().parents[1] / "test" / "sdk-behavior-cases.json").read_text(
        encoding="utf8"
    )
)


def _config(handler: Any) -> ClientConfig:
    """One attempt, no idempotency header, fake transport."""
    config = ClientConfig(
        base_url=FIXTURE["baseUrl"],
        auth=ClientAuthConfig(headers=dict(FIXTURE["authHeaders"])),
        retry=RetryConfig(max_attempts=1),
        idempotency=IdempotencyConfig(enabled=False, methods=()),
    )
    config._sync_client = httpx.Client(transport=httpx.MockTransport(handler))
    return config


def _build_path(case: dict[str, Any]) -> str:
    path = case["request"]["pathTemplate"]
    for name, value in case["request"]["pathParameters"].items():
        path = path.replace("{" + name + "}", encode_path_segment(value))
    return path


def _normalize(url: str) -> str:
    return url.replace("%20", "+")


@pytest.mark.parametrize("case", FIXTURE["cases"], ids=lambda case: case["id"])
def test_behavior_case(case: dict[str, Any]) -> None:
    request_spec = case["request"]
    response_spec = case["response"]
    seen: dict[str, httpx.Request] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        seen["request"] = request
        headers = {}
        if response_spec.get("mediaType"):
            headers["content-type"] = response_spec["mediaType"]
        if response_spec["status"] == 204:
            return httpx.Response(204, headers=headers)
        return httpx.Response(
            response_spec["status"], content=response_spec["body"], headers=headers
        )

    params: dict[str, Any] = {}
    if request_spec is not None:
        for parameter in request_spec["query"]:
            serialized = serialize_query(
                [(parameter["name"], parameter["value"], parameter["style"], parameter["explode"])]
            )
            if parameter["serialized"] is not None:
                assert serialized.get(parameter["name"]) == parameter["serialized"], (
                    "query serialization for " + parameter["name"]
                )
            params.update(serialized)

    config = _config(handler)
    try:
        kwargs: dict[str, Any] = {
            "params": params,
            "operation_id": case["operationId"],
            "response_decoder": response_spec["kind"],
            "config": config,
        }
        if request_spec is not None:
            if request_spec.get("bodyKind") is not None:
                kwargs["json"] = request_spec["body"]
                kwargs["content_type"] = request_spec["contentType"]
            if request_spec["headers"]:
                kwargs["extra_headers"] = request_spec["headers"]
        method = request_spec["method"] if request_spec else "GET"
        path = _build_path(case) if request_spec else "/behavior/" + case["id"]

        if response_spec["status"] >= 400:
            with pytest.raises(SdkHttpError) as raised:
                sdk_request_sync(method, path, **kwargs)
            assert raised.value.status_code == response_spec["status"]
            error_kind = response_spec.get("errorKind")
            expected_class = f"Sdk{error_kind}Error" if error_kind else "SdkHttpError"
            assert type(raised.value).__name__ == expected_class
            if "value" in response_spec:
                assert raised.value.body == response_spec["value"]
        else:
            response = sdk_request_sync(method, path, **kwargs)
            assert response.status_code == response_spec["status"]
            if "value" in response_spec:
                expected = response_spec["value"]
                actual = response.data
                if response_spec["kind"] == "bytes":
                    actual = len(actual or b"")
                assert actual == expected

        if request_spec is not None:
            sent = seen["request"]
            assert sent.method == case["expect"]["method"]
            assert _normalize(str(sent.url)) == _normalize(case["expect"]["url"])
            for name, value in case["expect"]["headers"].items():
                if name == "content-type" and request_spec.get("bodyKind") == "multipart":
                    assert sent.headers.get(name, "").startswith("multipart/form-data")
                    continue
                assert sent.headers.get(name) == value, "header " + name
            # Only a JSON body is compared byte-for-byte: the request layer owns
            # form/multipart encoding, whose field order and boundary vary.
            if case["expect"]["bodyText"] is not None and request_spec.get("bodyKind") == "json":
                assert sent.content.decode("utf8") == case["expect"]["bodyText"]
    finally:
        config.close()
