# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import dataclasses
import importlib
import inspect
import json
import os
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any

import pytest

import wakapi_unofficial_sdk as sdk
from wakapi_unofficial_sdk.wire import to_wire

CASES = json.loads(
    (Path(__file__).resolve().parents[1] / "test" / "sdk-method-cases.json").read_text(
        encoding="utf8"
    )
)["cases"]


def _normalize_name(value: str) -> str:
    return "".join(character for character in value.lower() if character.isalnum())


def _normal(value: Any) -> Any:
    if dataclasses.is_dataclass(value) and not isinstance(value, type):
        return _normal(dataclasses.asdict(value))
    if hasattr(value, "model_dump"):
        # Wire names: a renamed attribute (class_, na_ve) cannot be matched back to its key.
        return _normal(value.model_dump(mode="json", by_alias=True))
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, bytes):
        return list(value)
    if isinstance(value, dict):
        return {str(key): _normal(child) for key, child in value.items()}
    if isinstance(value, (list, tuple)):
        return [_normal(child) for child in value]
    if hasattr(value, "__dict__"):
        return _normal(vars(value))
    return value


def _matches(actual: Any, expected: Any) -> bool:
    if isinstance(expected, dict):
        if not isinstance(actual, dict):
            return False
        actual_by_name = {_normalize_name(str(key)): value for key, value in actual.items()}
        # An exact key wins: distinct wire keys (foo-bar, foo_bar) share a normalized name.
        return all(
            _matches(actual[key], value)
            if key in actual
            else _normalize_name(str(key)) in actual_by_name
            and _matches(actual_by_name[_normalize_name(str(key))], value)
            for key, value in expected.items()
        )
    if isinstance(expected, list):
        return (
            isinstance(actual, list)
            and len(actual) == len(expected)
            and all(_matches(item, expected[index]) for index, item in enumerate(actual))
        )
    return actual == expected


def _method(case: dict[str, Any]) -> Any:
    # Functions live in their namespace module (wakapi_unofficial_sdk.sdk.<owner>), not
    # on the package root, so an owner has to be imported before the lookup.
    owner = case.get("owner")
    if owner:
        module = importlib.import_module("wakapi_unofficial_sdk.sdk." + owner)
        return getattr(module, case["methodName"])
    if hasattr(sdk, case["methodName"]):
        return getattr(sdk, case["methodName"])
    # Class style binds each function to the client class its sdk module declares.
    module = importlib.import_module("wakapi_unofficial_sdk.sdk")
    client_class = next(
        value
        for value in vars(module).values()
        if isinstance(value, type) and value.__module__ == module.__name__
    )
    return getattr(client_class(sdk.get_client_config()), case["methodName"])


def _params(params_class: Any, by_name: dict[str, Any]) -> Any:
    # Filled like keyword arguments, matched by name and left unvalidated, so
    # both argument styles send the same values.
    if hasattr(params_class, "model_fields"):
        names = list(params_class.model_fields)
    elif dataclasses.is_dataclass(params_class):
        names = [field.name for field in dataclasses.fields(params_class)]
    else:
        names = [*params_class.__required_keys__, *params_class.__optional_keys__]
    values = {
        name: by_name[_normalize_name(name)] for name in names if _normalize_name(name) in by_name
    }
    return getattr(params_class, "model_construct", params_class)(**values)


def _wire_keyed(function: Any, value: Any) -> Any:
    # A dataclass or TypedDict result keeps idiomatic names (class_, na_ve); the
    # SDK's own mapping restores the wire keys, as model_dump(by_alias=True) does.
    annotation = inspect.signature(function).return_annotation
    if not isinstance(annotation, str) or not (
        isinstance(value, dict) or dataclasses.is_dataclass(value)
    ):
        return value
    return to_wire(value, annotation.split(" | ")[0])


async def _invoke(case: dict[str, Any]) -> Any:
    function = _method(case)
    signature = inspect.signature(function)
    arguments = case["arguments"]
    by_name = {_normalize_name(name): value for name, value in arguments.items()}
    positional: list[Any] = []
    keywords: dict[str, Any] = {}
    parameters = list(signature.parameters.values())
    for index, parameter in enumerate(parameters):
        normalized = _normalize_name(parameter.name)
        if normalized in {"config", "clientconfig"}:
            value = sdk.get_client_config()
        elif parameter.name == "params":
            # Object style takes the params class declared beside the method.
            module = sys.modules[getattr(function, "func", function).__module__]
            value = _params(getattr(module, parameter.annotation.split(" | ")[0]), by_name)
        elif parameter.name in {"options", "request"}:
            value = arguments
        elif normalized in by_name:
            value = by_name[normalized]
        elif parameter.default is not inspect.Parameter.empty:
            continue
        else:
            value = arguments.get(case["argumentOrder"][min(index, len(case["argumentOrder"]) - 1)])
        if parameter.kind is inspect.Parameter.POSITIONAL_ONLY:
            positional.append(value)
        else:
            keywords[parameter.name] = value
    result = function(*positional, **keywords)
    if inspect.isawaitable(result):
        return await result
    if hasattr(result, "__aiter__"):
        events = [item async for item in result]
        return events[0] if len(events) == 1 else events
    return result


@pytest.mark.asyncio
@pytest.mark.parametrize("case", CASES, ids=lambda case: case["id"])
async def test_generated_method_reaches_mock_and_decodes_response(
    case: dict[str, Any],
) -> None:
    base_url = os.environ.get("SDK_METHOD_TEST_BASE_URL")
    if not base_url:
        pytest.skip("run ./scripts/test to start the generated mock server")
    sdk.configure_client(base_url=base_url)
    actual = _normal(_wire_keyed(_method(case), await _invoke(case)))
    response = case["response"]
    if response["kind"] == "empty":
        assert actual is None
    elif response["kind"] == "bytes":
        assert len(actual) == response["byteLength"]
    else:
        assert _matches(actual, response["expected"]), (
            f"{case['methodName']} returned {actual!r}, expected representative "
            f"{response['expected']!r}"
        )
