# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from ..client import ClientConfig, LoggingConfig
from .badges import _BadgesNamespace
from .diagnostics import _DiagnosticsNamespace
from .heartbeat import _HeartbeatNamespace
from .misc import _MiscNamespace
from .summary import _SummaryNamespace
from .wakatime import _WakatimeNamespace


class Wakapi:
    def __init__(self, config: ClientConfig) -> None:
        self._config = config
        self.badges = _BadgesNamespace(config)
        self.wakatime = _WakatimeNamespace(config)
        self.heartbeat = _HeartbeatNamespace(config)
        self.misc = _MiscNamespace(config)
        self.diagnostics = _DiagnosticsNamespace(config)
        self.summary = _SummaryNamespace(config)

    def set_logging_config(
        self, config: LoggingConfig | None = None, **fields: Any
    ) -> LoggingConfig:
        """Turn SDK logging on and configure it.

        Logging is OFF by default — this SDK reports nothing until you call this
        (or construct the client with logging enabled). Reports go to the endpoint
        this build was generated with, or to the endpoint you pass; with neither,
        nothing is sent. Pass enabled=False to turn logging back off.
        """
        if self._config.logging is None:
            self._config.logging = LoggingConfig()
        current = self._config.logging
        if config is not None:
            for key, value in vars(config).items():
                if key != "enabled":
                    setattr(current, key, value)
        current.enabled = True
        for key, value in fields.items():
            if not hasattr(current, key):
                raise TypeError(f"LoggingConfig has no field {key!r}")
            setattr(current, key, value)
        return current


__all__ = ["Wakapi"]
