# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.badges import get_badge, get_badge_sync


class _BadgesNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_badge, config)
        self.get.__doc__ = get_badge.__doc__
        self.get_sync = partial(get_badge_sync, config)
        self.get_sync.__doc__ = get_badge_sync.__doc__
