# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.diagnostics import post_diagnostics, post_diagnostics_sync


class _DiagnosticsNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.post = partial(post_diagnostics, config)
        self.post.__doc__ = post_diagnostics.__doc__
        self.post_sync = partial(post_diagnostics_sync, config)
        self.post_sync.__doc__ = post_diagnostics_sync.__doc__
