# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.heartbeat import (
    get_heartbeats,
    get_heartbeats_sync,
    post_heartbeat,
    post_heartbeat_sync,
    post_heartbeat2,
    post_heartbeat2_sync,
    post_heartbeat3,
    post_heartbeat3_sync,
    post_heartbeat4,
    post_heartbeat4_sync,
    post_heartbeat5,
    post_heartbeat5_sync,
    post_heartbeat6,
    post_heartbeat6_sync,
    post_heartbeat7,
    post_heartbeat7_sync,
    post_heartbeat8,
    post_heartbeat8_sync,
)


class _HeartbeatNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_heartbeats, config)
        self.get.__doc__ = get_heartbeats.__doc__
        self.get_sync = partial(get_heartbeats_sync, config)
        self.get_sync.__doc__ = get_heartbeats_sync.__doc__
        self.post3 = partial(post_heartbeat3, config)
        self.post3.__doc__ = post_heartbeat3.__doc__
        self.post3_sync = partial(post_heartbeat3_sync, config)
        self.post3_sync.__doc__ = post_heartbeat3_sync.__doc__
        self.post7 = partial(post_heartbeat7, config)
        self.post7.__doc__ = post_heartbeat7.__doc__
        self.post7_sync = partial(post_heartbeat7_sync, config)
        self.post7_sync.__doc__ = post_heartbeat7_sync.__doc__
        self.post = partial(post_heartbeat, config)
        self.post.__doc__ = post_heartbeat.__doc__
        self.post_sync = partial(post_heartbeat_sync, config)
        self.post_sync.__doc__ = post_heartbeat_sync.__doc__
        self.post5 = partial(post_heartbeat5, config)
        self.post5.__doc__ = post_heartbeat5.__doc__
        self.post5_sync = partial(post_heartbeat5_sync, config)
        self.post5_sync.__doc__ = post_heartbeat5_sync.__doc__
        self.post4 = partial(post_heartbeat4, config)
        self.post4.__doc__ = post_heartbeat4.__doc__
        self.post4_sync = partial(post_heartbeat4_sync, config)
        self.post4_sync.__doc__ = post_heartbeat4_sync.__doc__
        self.post8 = partial(post_heartbeat8, config)
        self.post8.__doc__ = post_heartbeat8.__doc__
        self.post8_sync = partial(post_heartbeat8_sync, config)
        self.post8_sync.__doc__ = post_heartbeat8_sync.__doc__
        self.post2 = partial(post_heartbeat2, config)
        self.post2.__doc__ = post_heartbeat2.__doc__
        self.post2_sync = partial(post_heartbeat2_sync, config)
        self.post2_sync.__doc__ = post_heartbeat2_sync.__doc__
        self.post6 = partial(post_heartbeat6, config)
        self.post6.__doc__ = post_heartbeat6.__doc__
        self.post6_sync = partial(post_heartbeat6_sync, config)
        self.post6_sync.__doc__ = post_heartbeat6_sync.__doc__
