# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.misc import get_health, get_health_sync


class _MiscNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get_health = partial(get_health, config)
        self.get_health.__doc__ = get_health.__doc__
        self.get_health_sync = partial(get_health_sync, config)
        self.get_health_sync.__doc__ = get_health_sync.__doc__
