# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.summary import get_summary, get_summary_sync


class _SummaryNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_summary, config)
        self.get.__doc__ = get_summary.__doc__
        self.get_sync = partial(get_summary_sync, config)
        self.get_sync.__doc__ = get_summary_sync.__doc__
