# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.wakatime import (
    get_all_time,
    get_all_time_sync,
    get_wakatime_leaders,
    get_wakatime_leaders_sync,
    get_wakatime_project,
    get_wakatime_project_sync,
    get_wakatime_projects,
    get_wakatime_projects_sync,
    get_wakatime_summaries,
    get_wakatime_summaries_sync,
    get_wakatime_user,
    get_wakatime_user_sync,
    get_wakatime_useragents,
    get_wakatime_useragents_sync,
    get_wakatimes_tats,
    get_wakatimes_tats_sync,
    statusbar,
    statusbar_sync,
)


class _WakatimeNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get_leaders = partial(get_wakatime_leaders, config)
        self.get_leaders.__doc__ = get_wakatime_leaders.__doc__
        self.get_leaders_sync = partial(get_wakatime_leaders_sync, config)
        self.get_leaders_sync.__doc__ = get_wakatime_leaders_sync.__doc__
        self.get_user = partial(get_wakatime_user, config)
        self.get_user.__doc__ = get_wakatime_user.__doc__
        self.get_user_sync = partial(get_wakatime_user_sync, config)
        self.get_user_sync.__doc__ = get_wakatime_user_sync.__doc__
        self.get_all_time = partial(get_all_time, config)
        self.get_all_time.__doc__ = get_all_time.__doc__
        self.get_all_time_sync = partial(get_all_time_sync, config)
        self.get_all_time_sync.__doc__ = get_all_time_sync.__doc__
        self.get_projects = partial(get_wakatime_projects, config)
        self.get_projects.__doc__ = get_wakatime_projects.__doc__
        self.get_projects_sync = partial(get_wakatime_projects_sync, config)
        self.get_projects_sync.__doc__ = get_wakatime_projects_sync.__doc__
        self.get_project = partial(get_wakatime_project, config)
        self.get_project.__doc__ = get_wakatime_project.__doc__
        self.get_project_sync = partial(get_wakatime_project_sync, config)
        self.get_project_sync.__doc__ = get_wakatime_project_sync.__doc__
        self.get_tats = partial(get_wakatimes_tats, config)
        self.get_tats.__doc__ = get_wakatimes_tats.__doc__
        self.get_tats_sync = partial(get_wakatimes_tats_sync, config)
        self.get_tats_sync.__doc__ = get_wakatimes_tats_sync.__doc__
        self.get_summaries = partial(get_wakatime_summaries, config)
        self.get_summaries.__doc__ = get_wakatime_summaries.__doc__
        self.get_summaries_sync = partial(get_wakatime_summaries_sync, config)
        self.get_summaries_sync.__doc__ = get_wakatime_summaries_sync.__doc__
        self.get_useragents = partial(get_wakatime_useragents, config)
        self.get_useragents.__doc__ = get_wakatime_useragents.__doc__
        self.get_useragents_sync = partial(get_wakatime_useragents_sync, config)
        self.get_useragents_sync.__doc__ = get_wakatime_useragents_sync.__doc__
        self.statusbar = partial(statusbar, config)
        self.statusbar.__doc__ = statusbar.__doc__
        self.statusbar_sync = partial(statusbar_sync, config)
        self.statusbar_sync.__doc__ = statusbar_sync.__doc__
