# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import wakapi_unofficial_sdk.types as _response_types
from wakapi_unofficial_sdk.client import (
    ClientConfig,
    RequestOptions,
    encode_path_segment,
    sdk_request,
    sdk_request_sync,
)
from wakapi_unofficial_sdk.types import V1BadgeData
from wakapi_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_badge(
    _client_config: ClientConfig,
    user: str,
    interval: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str,
    filter: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1BadgeData:
    """Retrieves badge data for a user, interval, and filter in a format compatible with
    Shields.io. Use `interval` to choose the aggregation period and `filter` to select
    an entity such as a project or language; public data access must be enabled for the
    user.

    Retrieve total time for a given entity (e.g. a project) within a given range (e.g.
    one week) in a format compatible with [Shields.io](https://shields.io/endpoint).
    Requires public data access to be allowed.

    Args:
        user: User ID to fetch data for
        interval: Interval to aggregate data for
        filter: Filter to apply (e.g. 'project:wakapi' or 'language:Go')
    """

    _resp = await sdk_request(
        "GET",
        f"/compat/shields/v1/{encode_path_segment(user)}/{encode_path_segment(interval)}/{encode_path_segment(filter)}",
        operation_id="get_badge",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1BadgeData"), V1BadgeData
    )


def get_badge_sync(
    _client_config: ClientConfig,
    user: str,
    interval: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str,
    filter: str,
    *,
    request_options: RequestOptions | None = None,
) -> V1BadgeData:
    """Retrieves badge data for a user, interval, and filter in a format compatible with
    Shields.io. Use `interval` to choose the aggregation period and `filter` to select
    an entity such as a project or language; public data access must be enabled for the
    user.

    Retrieve total time for a given entity (e.g. a project) within a given range (e.g.
    one week) in a format compatible with [Shields.io](https://shields.io/endpoint).
    Requires public data access to be allowed.

    Args:
        user: User ID to fetch data for
        interval: Interval to aggregate data for
        filter: Filter to apply (e.g. 'project:wakapi' or 'language:Go')
    """

    _resp = sdk_request_sync(
        "GET",
        f"/compat/shields/v1/{encode_path_segment(user)}/{encode_path_segment(interval)}/{encode_path_segment(filter)}",
        operation_id="get_badge",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "V1BadgeData"), V1BadgeData
    )


__all__ = [
    "get_badge",
    "get_badge_sync",
]
