# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from wakapi_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from wakapi_unofficial_sdk.wire import to_wire


async def post_diagnostics(
    _client_config: ClientConfig,
    architecture: str | NotGiven = NOT_GIVEN,
    cli_version: str | NotGiven = NOT_GIVEN,
    id: int | NotGiven = NOT_GIVEN,
    logs: str | NotGiven = NOT_GIVEN,
    platform: str | NotGiven = NOT_GIVEN,
    plugin: str | NotGiven = NOT_GIVEN,
    stacktrace: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits a diagnostics object sent by the WakaTime CLI. Include diagnostic details
    such as the CLI version, platform, logs, or stack trace to provide context for the
    reported issue.

    Args:
        architecture: Optional `string` value serialized in the `architecture` wire field.
        cli_version: Optional `string` value serialized in the `cli_version` wire field.
        id: Optional `integer` value serialized in the `id` wire field.
        logs: Optional `string` value serialized in the `logs` wire field.
        platform: Optional `string` value serialized in the `platform` wire field.
        plugin: Optional `string` value serialized in the `plugin` wire field.
        stacktrace: Optional `string` value serialized in the `stacktrace` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/plugins/errors",
        json=omit_unset(
            {
                "architecture": (
                    NOT_GIVEN if architecture is NOT_GIVEN else to_wire(architecture, "str")
                ),
                "cli_version": (
                    NOT_GIVEN if cli_version is NOT_GIVEN else to_wire(cli_version, "str")
                ),
                "id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "int")),
                "logs": (NOT_GIVEN if logs is NOT_GIVEN else to_wire(logs, "str")),
                "platform": (NOT_GIVEN if platform is NOT_GIVEN else to_wire(platform, "str")),
                "plugin": (NOT_GIVEN if plugin is NOT_GIVEN else to_wire(plugin, "str")),
                "stacktrace": (
                    NOT_GIVEN if stacktrace is NOT_GIVEN else to_wire(stacktrace, "str")
                ),
            }
        ),
        operation_id="post_diagnostics",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def post_diagnostics_sync(
    _client_config: ClientConfig,
    architecture: str | NotGiven = NOT_GIVEN,
    cli_version: str | NotGiven = NOT_GIVEN,
    id: int | NotGiven = NOT_GIVEN,
    logs: str | NotGiven = NOT_GIVEN,
    platform: str | NotGiven = NOT_GIVEN,
    plugin: str | NotGiven = NOT_GIVEN,
    stacktrace: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits a diagnostics object sent by the WakaTime CLI. Include diagnostic details
    such as the CLI version, platform, logs, or stack trace to provide context for the
    reported issue.

    Args:
        architecture: Optional `string` value serialized in the `architecture` wire field.
        cli_version: Optional `string` value serialized in the `cli_version` wire field.
        id: Optional `integer` value serialized in the `id` wire field.
        logs: Optional `string` value serialized in the `logs` wire field.
        platform: Optional `string` value serialized in the `platform` wire field.
        plugin: Optional `string` value serialized in the `plugin` wire field.
        stacktrace: Optional `string` value serialized in the `stacktrace` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/plugins/errors",
        json=omit_unset(
            {
                "architecture": (
                    NOT_GIVEN if architecture is NOT_GIVEN else to_wire(architecture, "str")
                ),
                "cli_version": (
                    NOT_GIVEN if cli_version is NOT_GIVEN else to_wire(cli_version, "str")
                ),
                "id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "int")),
                "logs": (NOT_GIVEN if logs is NOT_GIVEN else to_wire(logs, "str")),
                "platform": (NOT_GIVEN if platform is NOT_GIVEN else to_wire(platform, "str")),
                "plugin": (NOT_GIVEN if plugin is NOT_GIVEN else to_wire(plugin, "str")),
                "stacktrace": (
                    NOT_GIVEN if stacktrace is NOT_GIVEN else to_wire(stacktrace, "str")
                ),
            }
        ),
        operation_id="post_diagnostics",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


__all__ = [
    "post_diagnostics",
    "post_diagnostics_sync",
]
