# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

import wakapi_unofficial_sdk.types as _response_types
from wakapi_unofficial_sdk.client import ClientConfig, RequestOptions, sdk_request, sdk_request_sync


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_health(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Retrieves the application's health status. Use this endpoint to check the service's
    current health without supplying request parameters or a body.
    """

    _resp = await sdk_request(
        "GET",
        "/health",
        operation_id="get_health",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


def get_health_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> str:
    """Retrieves the application's health status. Use this endpoint to check the service's
    current health without supplying request parameters or a body.
    """

    _resp = sdk_request_sync(
        "GET",
        "/health",
        operation_id="get_health",
        response_decoder="text",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, str)


__all__ = [
    "get_health",
    "get_health_sync",
]
