# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, Literal

from pydantic import TypeAdapter

import wakapi_unofficial_sdk.types as _response_types
from wakapi_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from wakapi_unofficial_sdk.types import ModelsSummary
from wakapi_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


async def get_summary(
    _client_config: ClientConfig,
    interval: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str
    | NotGiven = NOT_GIVEN,
    from_: str | NotGiven = NOT_GIVEN,
    to: str | NotGiven = NOT_GIVEN,
    recompute: bool | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    label: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ModelsSummary:
    """Retrieves a summary of activity for the requested interval or date range. Use `from`
    and `to` to define the period, and apply project, language, editor, operating
    system, machine, or label filters to narrow the summary.

    Args:
        interval: Interval identifier
        from_: Start date (e.g. '2021-02-07')
        to: End date (e.g. '2021-02-08')
        recompute: Whether to recompute the summary from raw heartbeat or use cache
        project: Project to filter by
        language: Language to filter by
        editor: Editor to filter by
        operating_system: OS to filter by
        machine: Machine to filter by
        label: Project label to filter by
    """

    _resp = await sdk_request(
        "GET",
        "/summary",
        params=serialize_query(
            [
                ("interval", interval, "form", True),
                ("from", from_, "form", True),
                ("to", to, "form", True),
                ("recompute", recompute, "form", True),
                ("project", project, "form", True),
                ("language", language, "form", True),
                ("editor", editor, "form", True),
                ("operating_system", operating_system, "form", True),
                ("machine", machine, "form", True),
                ("label", label, "form", True),
            ]
        ),
        operation_id="get_summary",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ModelsSummary"), ModelsSummary
    )


def get_summary_sync(
    _client_config: ClientConfig,
    interval: Literal[
        "today",
        "yesterday",
        "week",
        "month",
        "year",
        "7_days",
        "last_7_days",
        "30_days",
        "last_30_days",
        "6_months",
        "last_6_months",
        "12_months",
        "last_12_months",
        "last_year",
        "any",
        "all_time",
    ]
    | str
    | NotGiven = NOT_GIVEN,
    from_: str | NotGiven = NOT_GIVEN,
    to: str | NotGiven = NOT_GIVEN,
    recompute: bool | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    label: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ModelsSummary:
    """Retrieves a summary of activity for the requested interval or date range. Use `from`
    and `to` to define the period, and apply project, language, editor, operating
    system, machine, or label filters to narrow the summary.

    Args:
        interval: Interval identifier
        from_: Start date (e.g. '2021-02-07')
        to: End date (e.g. '2021-02-08')
        recompute: Whether to recompute the summary from raw heartbeat or use cache
        project: Project to filter by
        language: Language to filter by
        editor: Editor to filter by
        operating_system: OS to filter by
        machine: Machine to filter by
        label: Project label to filter by
    """

    _resp = sdk_request_sync(
        "GET",
        "/summary",
        params=serialize_query(
            [
                ("interval", interval, "form", True),
                ("from", from_, "form", True),
                ("to", to, "form", True),
                ("recompute", recompute, "form", True),
                ("project", project, "form", True),
                ("language", language, "form", True),
                ("editor", editor, "form", True),
                ("operating_system", operating_system, "form", True),
                ("machine", machine, "form", True),
                ("label", label, "form", True),
            ]
        ),
        operation_id="get_summary",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ModelsSummary"), ModelsSummary
    )


__all__ = [
    "get_summary",
    "get_summary_sync",
]
