# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from wakapi_unofficial_sdk.client import NOT_GIVEN, NotGiven


class V1BadgeData(BaseModel):
    """Typed representation of the `V1BadgeData` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    color: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `color` wire field."""
    label: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `label` wire field."""
    message: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `message` wire field."""
    schema_version: int | NotGiven = Field(NOT_GIVEN, alias="schemaVersion")
    """Optional `integer` value serialized in the `schemaVersion` wire field."""
