# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from wakapi_unofficial_sdk.client import NOT_GIVEN, NotGiven


class ModelsDiagnostics(BaseModel):
    """Typed representation of the `ModelsDiagnostics` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    architecture: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `architecture` wire field."""
    cli_version: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `cli_version` wire field."""
    id: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `id` wire field."""
    logs: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `logs` wire field."""
    platform: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `platform` wire field."""
    plugin: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `plugin` wire field."""
    stacktrace: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `stacktrace` wire field."""
