# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from wakapi_unofficial_sdk.client import NOT_GIVEN, NotGiven


class ModelsHeartbeat(BaseModel):
    """Typed representation of the `ModelsHeartbeat` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    ai_input_tokens: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_input_tokens` wire field."""
    ai_line_changes: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_line_changes` wire field."""
    ai_output_tokens: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_output_tokens` wire field."""
    ai_prompt_length: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_prompt_length` wire field."""
    ai_session: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `ai_session` wire field."""
    branch: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `branch` wire field."""
    category: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `category` wire field."""
    created_at: float | NotGiven = NOT_GIVEN
    """https://gorm.io/docs/conventions.html#CreatedAt"""
    cursorpos: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `cursorpos` wire field."""
    editor: str | NotGiven = NOT_GIVEN
    """ignored because editor might be parsed differently by wakatime"""
    entity: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `entity` wire field."""
    human_line_changes: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `human_line_changes` wire field."""
    is_write: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_write` wire field."""
    language: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `language` wire field."""
    line_additions: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `line_additions` wire field."""
    line_deletions: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `line_deletions` wire field."""
    lineno: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `lineno` wire field."""
    lines: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `lines` wire field."""
    machine: str | NotGiven = NOT_GIVEN
    """ignored because wakatime api doesn't return machines currently"""
    operating_system: str | NotGiven = NOT_GIVEN
    """ignored because os might be parsed differently by wakatime"""
    project: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `project` wire field."""
    project_root_count: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `project_root_count` wire field."""
    time: float | NotGiven = NOT_GIVEN
    """
    note: on sqlite, table will have an additional column `time_real`, introduced "manually" by migration 20260111
    see https://github.com/muety/wakapi/issues/882 for details
    """
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    user_agent: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `user_agent` wire field."""


class V1HeartbeatEntry(BaseModel):
    """Typed representation of the `V1HeartbeatEntry` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    ai_input_tokens: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_input_tokens` wire field."""
    ai_line_changes: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_line_changes` wire field."""
    ai_output_tokens: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_output_tokens` wire field."""
    ai_prompt_length: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `ai_prompt_length` wire field."""
    ai_session: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `ai_session` wire field."""
    branch: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `branch` wire field."""
    category: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `category` wire field."""
    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    cursorpos: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `cursorpos` wire field."""
    entity: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `entity` wire field."""
    human_line_changes: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `human_line_changes` wire field."""
    id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `id` wire field."""
    is_write: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_write` wire field."""
    language: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `language` wire field."""
    line_additions: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `line_additions` wire field."""
    line_deletions: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `line_deletions` wire field."""
    lineno: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `lineno` wire field."""
    lines: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `lines` wire field."""
    machine_name_id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `machine_name_id` wire field."""
    project: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `project` wire field."""
    time: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `time` wire field."""
    type: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `type` wire field."""
    user_agent_id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `user_agent_id` wire field."""
    user_id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `user_id` wire field."""


class V1HeartbeatsResult(BaseModel):
    """Typed representation of the `V1HeartbeatsResult` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: list[V1HeartbeatEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `data` wire field."""
    end: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end` wire field."""
    start: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start` wire field."""
    timezone: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `timezone` wire field."""
