# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator

from wakapi_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_date


class ModelsSummary(BaseModel):
    """Typed representation of the `ModelsSummary` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    branches: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """branches are not persisted, but calculated at runtime in case a project Filter is applied"""
    categories: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `categories` wire field."""
    editors: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `editors` wire field."""
    entities: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """entities are not persisted, but calculated at runtime in case a project Filter is applied"""
    from_: datetime.date | NotGiven = Field(NOT_GIVEN, alias="from")
    """filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt"""
    labels: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """labels are not persisted, but calculated at runtime, i.e. when summary is retrieved"""
    languages: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `languages` wire field."""
    machines: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `machines` wire field."""
    operating_systems: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `operating_systems` wire field."""
    projects: list[ModelsSummaryItem] | NotGiven = NOT_GIVEN
    """
    Previously, all the following properties created a cascade foreign key constraint on the summary_items table
    back to this summary table resulting in 5 identical foreign key constraints on the summary_items table.
    This is not a problem for PostgreSQL, MySQL and SQLite, but for MSSQL (not supported anymore though), which complains about circular cascades on
    update/delete between these two tables. All of these created foreign key constraints are identical, so only one constraint is enough.
    MySQL will create a foreign key constraint for every property referencing other structs, even no constraint is specified in tags.
    So explicitly set gorm:"-" in all other properties to avoid creating duplicate foreign key constraints
    """
    to: datetime.date | NotGiven = NOT_GIVEN
    """filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt"""
    user_id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `user_id` wire field."""

    @field_validator("from_", mode="before")
    @classmethod
    def _validate_from_(cls, value):
        validate_date("from", value)
        return value

    @field_validator("to", mode="before")
    @classmethod
    def _validate_to(cls, value):
        validate_date("to", value)
        return value


class ModelsSummaryItem(BaseModel):
    """Typed representation of the `ModelsSummaryItem` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    key: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `key` wire field."""
    total: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total` wire field."""
