# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from wakapi_unofficial_sdk.client import NOT_GIVEN, NotGiven


class V1AllTimeData(BaseModel):
    """Typed representation of the `V1AllTimeData` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    is_up_to_date: bool | NotGiven = NOT_GIVEN
    """true if the stats are up to date; when false, a 202 response code is returned and stats will be refreshed soon>"""
    range: V1AllTimeRange | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `range` wire field."""
    text: str | NotGiven = NOT_GIVEN
    """total time logged since account created as human readable string>"""
    total_seconds: float | NotGiven = NOT_GIVEN
    """total number of seconds logged since account created"""


class V1AllTimeRange(BaseModel):
    """Typed representation of the `V1AllTimeRange` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    end: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end` wire field."""
    end_date: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end_date` wire field."""
    start: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start` wire field."""
    start_date: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start_date` wire field."""
    timezone: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `timezone` wire field."""


class V1AllTimeViewModel(BaseModel):
    """Typed representation of the `V1AllTimeViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: V1AllTimeData | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""


class V1LeadersCurrentUser(BaseModel):
    """Typed representation of the `V1LeadersCurrentUser` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    page: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `page` wire field."""
    rank: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `rank` wire field."""
    user: V1User | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `user` wire field."""


class V1LeadersEntry(BaseModel):
    """Typed representation of the `V1LeadersEntry` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    rank: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `rank` wire field."""
    running_total: V1LeadersRunningTotal | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `running_total` wire field."""
    user: V1User | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `user` wire field."""


class V1LeadersLanguage(BaseModel):
    """Typed representation of the `V1LeadersLanguage` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    total_seconds: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `total_seconds` wire field."""


class V1LeadersRange(BaseModel):
    """Typed representation of the `V1LeadersRange` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    end_date: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end_date` wire field."""
    end_text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end_text` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    start_date: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start_date` wire field."""
    start_text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start_text` wire field."""
    text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `text` wire field."""


class V1LeadersRunningTotal(BaseModel):
    """Typed representation of the `V1LeadersRunningTotal` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    daily_average: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `daily_average` wire field."""
    human_readable_daily_average: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `human_readable_daily_average` wire field."""
    human_readable_total: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `human_readable_total` wire field."""
    languages: list[V1LeadersLanguage] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `languages` wire field."""
    total_seconds: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `total_seconds` wire field."""


class V1LeadersViewModel(BaseModel):
    """Typed representation of the `V1LeadersViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    current_user: V1LeadersCurrentUser | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `current_user` wire field."""
    data: list[V1LeadersEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `data` wire field."""
    language: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `language` wire field."""
    page: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `page` wire field."""
    range: V1LeadersRange | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `range` wire field."""
    total_pages: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total_pages` wire field."""


class V1Project(BaseModel):
    """Typed representation of the `V1Project` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    human_readable_last_heartbeat_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `human_readable_last_heartbeat_at` wire field."""
    id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `id` wire field."""
    last_heartbeat_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `last_heartbeat_at` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    urlencoded_name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `urlencoded_name` wire field."""


class V1ProjectViewModel(BaseModel):
    """Typed representation of the `V1ProjectViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: V1Project | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""


class V1ProjectsViewModel(BaseModel):
    """Typed representation of the `V1ProjectsViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: list[V1Project] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `data` wire field."""


class V1StatsData(BaseModel):
    """Typed representation of the `V1StatsData` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    branches: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `branches` wire field."""
    categories: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `categories` wire field."""
    daily_average: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `daily_average` wire field."""
    days_including_holidays: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `days_including_holidays` wire field."""
    editors: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `editors` wire field."""
    end: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end` wire field."""
    human_readable_daily_average: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `human_readable_daily_average` wire field."""
    human_readable_range: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `human_readable_range` wire field."""
    human_readable_total: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `human_readable_total` wire field."""
    is_coding_activity_visible: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_coding_activity_visible` wire field."""
    is_other_usage_visible: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_other_usage_visible` wire field."""
    languages: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `languages` wire field."""
    machines: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `machines` wire field."""
    operating_systems: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `operating_systems` wire field."""
    projects: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `projects` wire field."""
    range: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `range` wire field."""
    start: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start` wire field."""
    status: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `status` wire field."""
    timezone: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `timezone` wire field."""
    total_seconds: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `total_seconds` wire field."""
    user_id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `user_id` wire field."""
    username: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `username` wire field."""


class V1StatsViewModel(BaseModel):
    """Typed representation of the `V1StatsViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: V1StatsData | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""


class V1StatusBarViewModel(BaseModel):
    """Typed representation of the `V1StatusBarViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    cached_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `cached_at` wire field."""
    data: V1SummariesData | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""


class V1SummariesCumulativeTotal(BaseModel):
    """Typed representation of the `V1SummariesCumulativeTotal` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    decimal: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `decimal` wire field."""
    digital: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `digital` wire field."""
    seconds: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `seconds` wire field."""
    text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `text` wire field."""


class V1SummariesDailyAverage(BaseModel):
    """Typed representation of the `V1SummariesDailyAverage` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    days_including_holidays: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `days_including_holidays` wire field."""
    days_minus_holidays: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `days_minus_holidays` wire field."""
    holidays: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `holidays` wire field."""
    seconds: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `seconds` wire field."""
    seconds_including_other_language: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `seconds_including_other_language` wire field."""
    text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `text` wire field."""
    text_including_other_language: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `text_including_other_language` wire field."""


class V1SummariesData(BaseModel):
    """Typed representation of the `V1SummariesData` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    branches: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `branches` wire field."""
    categories: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `categories` wire field."""
    dependencies: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `dependencies` wire field."""
    editors: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `editors` wire field."""
    entities: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `entities` wire field."""
    grand_total: V1SummariesGrandTotal | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `grand_total` wire field."""
    languages: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `languages` wire field."""
    machines: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `machines` wire field."""
    operating_systems: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `operating_systems` wire field."""
    projects: list[V1SummariesEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `projects` wire field."""
    range: V1SummariesRange | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `range` wire field."""


class V1SummariesEntry(BaseModel):
    """Typed representation of the `V1SummariesEntry` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    digital: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `digital` wire field."""
    hours: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `hours` wire field."""
    minutes: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `minutes` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    percent: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `percent` wire field."""
    seconds: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `seconds` wire field."""
    text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `text` wire field."""
    total_seconds: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `total_seconds` wire field."""


class V1SummariesGrandTotal(BaseModel):
    """Typed representation of the `V1SummariesGrandTotal` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    digital: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `digital` wire field."""
    hours: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `hours` wire field."""
    minutes: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `minutes` wire field."""
    text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `text` wire field."""
    total_seconds: float | NotGiven = NOT_GIVEN
    """Optional `number` value serialized in the `total_seconds` wire field."""


class V1SummariesRange(BaseModel):
    """Typed representation of the `V1SummariesRange` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    date: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `date` wire field."""
    end: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end` wire field."""
    start: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start` wire field."""
    text: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `text` wire field."""
    timezone: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `timezone` wire field."""


class V1SummariesViewModel(BaseModel):
    """Typed representation of the `V1SummariesViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    cumulative_total: V1SummariesCumulativeTotal | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `cumulative_total` wire field."""
    daily_average: V1SummariesDailyAverage | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `daily_average` wire field."""
    data: list[V1SummariesData] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `data` wire field."""
    end: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `end` wire field."""
    start: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `start` wire field."""


class V1User(BaseModel):
    """Typed representation of the `V1User` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    created_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `created_at` wire field."""
    display_name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `display_name` wire field."""
    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    full_name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `full_name` wire field."""
    id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `id` wire field."""
    is_email_confirmed: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_email_confirmed` wire field."""
    is_email_public: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `is_email_public` wire field."""
    last_heartbeat_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `last_heartbeat_at` wire field."""
    last_plugin_name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `last_plugin_name` wire field."""
    last_project: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `last_project` wire field."""
    modified_at: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `modified_at` wire field."""
    photo: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `photo` wire field."""
    timezone: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `timezone` wire field."""
    username: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `username` wire field."""
    website: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `website` wire field."""


class V1UserAgentEntry(BaseModel):
    """Typed representation of the `V1UserAgentEntry` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    editor: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `editor` wire field."""
    first_seen: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `first_seen` wire field."""
    id: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `id` wire field."""
    is_browser_extension: bool | NotGiven = NOT_GIVEN
    """currently not implemented"""
    is_desktop_app: bool | NotGiven = NOT_GIVEN
    """currently not implemented"""
    last_seen: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `last_seen` wire field."""
    os: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `os` wire field."""
    value: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `value` wire field."""
    version: str | NotGiven = NOT_GIVEN
    """currently not implemented"""
