# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from wakapi_unofficial_sdk.client import NOT_GIVEN, NotGiven
from wakapi_unofficial_sdk.types.wakatime_part001 import V1User, V1UserAgentEntry


class V1UserAgentsViewModel(BaseModel):
    """Typed representation of the `V1UserAgentsViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: list[V1UserAgentEntry] | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `data` wire field."""
    total_pages: int | NotGiven = NOT_GIVEN
    """Optional `integer` value serialized in the `total_pages` wire field."""


class V1UserViewModel(BaseModel):
    """Typed representation of the `V1UserViewModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    data: V1User | NotGiven = NOT_GIVEN
    """Optional object value serialized in the `data` wire field."""
