# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import json as _json
from collections.abc import AsyncIterator, Iterator
from dataclasses import dataclass
from typing import Any, Generic, TypeVar

from ._client_config import NOT_GIVEN, ClientConfig, StreamRequestOptions, _client_config
from ._client_transport import _apply_auth, _apply_auth_sync, _body_kwargs, _request_id, _strip_none
from .errors import SdkHttpError, SdkStreamParseError

_T = TypeVar("_T")


@dataclass
class SdkStreamEvent(Generic[_T]):
    """One framed record or raw chunk yielded by :func:`sdk_stream`."""

    event: str
    data: _T
    id: str | None
    retry: int | None


def _parse_stream_json(raw: str) -> Any:
    try:
        return _json.loads(raw)
    except _json.JSONDecodeError as error:
        raise SdkStreamParseError(raw, error) from error


def _is_stream_done(raw: str) -> bool:
    return raw.strip() == "[DONE]"


async def sdk_stream(
    method: str,
    path: str,
    *,
    params: dict[str, Any] | None = None,
    json: Any = NOT_GIVEN,
    extra_headers: dict[str, str] | None = None,
    content_type: str = "application/json",
    operation_id: str = "",
    stream_format: str = "sse",
    chunk_domain: str = "bytes",
    config: ClientConfig | None = None,
    request_options: StreamRequestOptions | None = None,
) -> AsyncIterator[SdkStreamEvent[Any]]:
    """Opens a framed or raw stream and yields records. Bypasses the retry loop
    and idempotency layer — streaming connections are long-lived; reconnect
    is the consumer's responsibility. Auth is applied normally."""
    cfg = config or _client_config
    method = method.upper()
    if path.startswith(("http://", "https://")):
        url = path
    else:
        url = f"{cfg.base_url or ''}{path}"
    clean_params = _strip_none(params) or {}
    accept = {
        "sse": "text/event-stream",
        "ndjson": "application/x-ndjson",
    }.get(stream_format, "application/octet-stream")
    headers: dict[str, str] = {"Accept": accept}
    extra_query: dict[str, str] = {}
    if extra_headers:
        headers.update(extra_headers)
    # After the operation's headers, so an apiKey cookie joins its cookies.
    await _apply_auth(cfg, headers, extra_query, operation_id)
    if request_options:
        headers.update(request_options.get("headers", {}))
    if json is not NOT_GIVEN and not content_type.startswith("multipart/form-data"):
        headers["Content-Type"] = content_type
    merged = {**clean_params, **extra_query} if extra_query else clean_params

    async with cfg.client.stream(
        method,
        url,
        headers=headers,
        params=merged,
        **_body_kwargs(content_type, json, headers),
    ) as response:
        if not response.is_success:
            body = (await response.aread()).decode("utf-8", errors="replace")
            raise SdkHttpError.for_status(
                status_code=response.status_code,
                status_text=response.reason_phrase,
                body=body,
                headers={k.lower(): v for k, v in response.headers.items()},
                request_id=_request_id(response.headers),
            )
        if stream_format == "chunked":
            async for chunk in response.aiter_raw():
                data: Any = chunk.decode("utf-8") if chunk_domain == "text" else chunk
                yield SdkStreamEvent(event="chunk", data=data, id=None, retry=None)
            return
        if stream_format == "ndjson":
            # strip() also drops the RS that starts a JSON text sequence record.
            async for line in response.aiter_lines():
                if line.strip():
                    if _is_stream_done(line):
                        return
                    yield SdkStreamEvent(
                        event="message",
                        data=_parse_stream_json(line.strip()),
                        id=None,
                        retry=None,
                    )
            return
        event_name: str | None = None
        event_id: str | None = None
        event_retry: int | None = None
        data_lines: list[str] = []
        async for line in response.aiter_lines():
            if line == "":
                if data_lines:
                    raw = "\n".join(data_lines)
                    if _is_stream_done(raw):
                        return
                    parsed: Any = raw
                    trimmed = raw.lstrip()
                    if trimmed.startswith(("{", "[")):
                        parsed = _parse_stream_json(raw)
                    yield SdkStreamEvent(
                        event=event_name or "message",
                        data=parsed,
                        id=event_id,
                        retry=event_retry,
                    )
                event_name = None
                data_lines = []
                continue
            if line.startswith(":"):
                continue  # comment
            field_sep = line.find(":")
            field_name = line if field_sep == -1 else line[:field_sep]
            value = "" if field_sep == -1 else line[field_sep + 1 :]
            value = value.removeprefix(" ")
            if field_name == "event":
                event_name = value
            elif field_name == "data":
                data_lines.append(value)
            elif field_name == "id":
                event_id = value
            elif field_name == "retry":
                try:
                    event_retry = int(value)
                except ValueError:
                    pass


def sdk_stream_sync(
    method: str,
    path: str,
    *,
    params: dict[str, Any] | None = None,
    json: Any = NOT_GIVEN,
    extra_headers: dict[str, str] | None = None,
    content_type: str = "application/json",
    operation_id: str = "",
    stream_format: str = "sse",
    chunk_domain: str = "bytes",
    config: ClientConfig | None = None,
    request_options: StreamRequestOptions | None = None,
) -> Iterator[SdkStreamEvent[Any]]:
    """Synchronous counterpart to :func:`sdk_stream`. Yields parsed SSE events
    using the sync httpx client. Same semantics — auth applied, retry/idempotency
    bypassed, caller owns reconnect."""
    cfg = config or _client_config
    method = method.upper()
    if path.startswith(("http://", "https://")):
        url = path
    else:
        url = f"{cfg.base_url or ''}{path}"
    clean_params = _strip_none(params) or {}
    accept = {
        "sse": "text/event-stream",
        "ndjson": "application/x-ndjson",
    }.get(stream_format, "application/octet-stream")
    headers: dict[str, str] = {"Accept": accept}
    extra_query: dict[str, str] = {}
    if extra_headers:
        headers.update(extra_headers)
    # After the operation's headers, so an apiKey cookie joins its cookies.
    _apply_auth_sync(cfg, headers, extra_query, operation_id)
    if request_options:
        headers.update(request_options.get("headers", {}))
    if json is not NOT_GIVEN and not content_type.startswith("multipart/form-data"):
        headers["Content-Type"] = content_type
    merged = {**clean_params, **extra_query} if extra_query else clean_params

    with cfg.sync_client.stream(
        method,
        url,
        headers=headers,
        params=merged,
        **_body_kwargs(content_type, json, headers),
    ) as response:
        if not response.is_success:
            body = response.read().decode("utf-8", errors="replace")
            raise SdkHttpError.for_status(
                status_code=response.status_code,
                status_text=response.reason_phrase,
                body=body,
                headers={k.lower(): v for k, v in response.headers.items()},
                request_id=_request_id(response.headers),
            )
        if stream_format == "chunked":
            for chunk in response.iter_raw():
                data: Any = chunk.decode("utf-8") if chunk_domain == "text" else chunk
                yield SdkStreamEvent(event="chunk", data=data, id=None, retry=None)
            return
        if stream_format == "ndjson":
            # strip() also drops the RS that starts a JSON text sequence record.
            for line in response.iter_lines():
                if line.strip():
                    if _is_stream_done(line):
                        return
                    yield SdkStreamEvent(
                        event="message",
                        data=_parse_stream_json(line.strip()),
                        id=None,
                        retry=None,
                    )
            return
        event_name: str | None = None
        event_id: str | None = None
        event_retry: int | None = None
        data_lines: list[str] = []
        for line in response.iter_lines():
            if line == "":
                if data_lines:
                    raw = "\n".join(data_lines)
                    if _is_stream_done(raw):
                        return
                    parsed: Any = raw
                    trimmed = raw.lstrip()
                    if trimmed.startswith(("{", "[")):
                        parsed = _parse_stream_json(raw)
                    yield SdkStreamEvent(
                        event=event_name or "message",
                        data=parsed,
                        id=event_id,
                        retry=event_retry,
                    )
                event_name = None
                data_lines = []
                continue
            if line.startswith(":"):
                continue  # comment
            field_sep = line.find(":")
            field_name = line if field_sep == -1 else line[:field_sep]
            value = "" if field_sep == -1 else line[field_sep + 1 :]
            value = value.removeprefix(" ")
            if field_name == "event":
                event_name = value
            elif field_name == "data":
                data_lines.append(value)
            elif field_name == "id":
                event_id = value
            elif field_name == "retry":
                try:
                    event_retry = int(value)
                except ValueError:
                    pass
