# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import asyncio
import random
import time
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import TypeVar

from .errors import SdkNetworkError, SdkTimeoutError

_T = TypeVar("_T")


@dataclass
class WaitForConfig:
    interval_s: float = 1.0
    max_interval_s: float = 30.0
    timeout_s: float = 600.0


async def wait_for(
    poll: Callable[[], Awaitable[_T]],
    is_terminal: Callable[[_T], tuple[bool, bool, str | None]],
    config: WaitForConfig | None = None,
) -> _T:
    """Polls a long-running operation until terminal. ``is_terminal`` returns
    ``(done, failed, reason)``. Raises :class:`SdkTimeoutError` on deadline."""
    cfg = config or WaitForConfig()
    deadline = time.monotonic() + cfg.timeout_s
    interval = cfg.interval_s
    while True:
        result = await poll()
        done, failed, reason = is_terminal(result)
        if done:
            if failed:
                raise SdkNetworkError(RuntimeError(f"Operation failed: {reason or 'unknown'}"))
            return result
        if time.monotonic() >= deadline:
            raise SdkTimeoutError(int(cfg.timeout_s * 1000))
        jitter = random.random() * cfg.interval_s
        await asyncio.sleep(min(interval + jitter, cfg.max_interval_s))
        interval = min(interval * 2, cfg.max_interval_s)
