# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import asyncio
import random
import time
import uuid
from collections.abc import Sequence
from email.utils import parsedate_to_datetime
from typing import Any
from urllib.parse import parse_qsl, quote, urlencode

import httpx

from ._client_config import (
    _ALWAYS_RETRYABLE_STATUSES,
    _IDEMPOTENT_METHODS,
    _REQUEST_ID_HEADERS,
    NOT_GIVEN,
    ClientConfig,
    Middleware,
    MultipartPart,
    RequestOptions,
    RetryConfig,
    SdkNext,
    SdkRequest,
    SyncMiddleware,
    SyncSdkNext,
    UploadFile,
    _client_config,
    _wire_json,
    _wire_scalar,
    add_breadcrumb,
)
from ._client_logging import _log_error, _log_error_sync
from .errors import SdkHttpError, SdkNetworkError, SdkResponse, SdkTimeoutError


async def _apply_auth(
    config: ClientConfig,
    headers: dict[str, str],
    query: dict[str, str],
    operation_id: str,
) -> None:
    auth = config.auth

    if auth is None:
        return
    headers.update(auth.headers)

    if auth.api_key_auth:
        headers["Authorization"] = auth.api_key_auth


def _apply_auth_sync(
    config: ClientConfig,
    headers: dict[str, str],
    query: dict[str, str],
    operation_id: str,
) -> None:
    """Sync variant of :func:`_apply_auth` used by ``*_sync`` method paths."""
    auth = config.auth

    if auth is None:
        return
    headers.update(auth.headers)

    if auth.api_key_auth:
        headers["Authorization"] = auth.api_key_auth


def _url_with_query(url: str, params: dict[str, Any] | None) -> str:
    """URL with `params` appended, encoded per RFC 3986.

    httpx percent-encodes `*` when it builds a query from `params`, while the
    RFC lists it as a sub-delimiter that is legal unencoded — and every other
    Octri runtime leaves it bare. Encoding here keeps the wire format identical
    across languages; httpx preserves a query it is handed inside the URL.
    """
    if not params:
        return url
    pairs: list[tuple[str, str]] = []
    for name, value in params.items():
        if isinstance(value, (list, tuple)):
            pairs.extend((name, str(item)) for item in value)
        else:
            pairs.append((name, str(value)))
    encoded = urlencode(pairs, safe="*", quote_via=quote)
    return f"{url}{'&' if '?' in url else '?'}{encoded}"


def _strip_none(params: dict[str, Any] | None) -> dict[str, Any] | None:
    if params is None:
        return None
    return {k: v for k, v in params.items() if v is not None}


def _body_kwargs(
    content_type: str,
    body_json: Any,
    headers: dict[str, str] | None = None,
) -> dict[str, Any]:
    """httpx call kwargs for a request body. multipart/form-data is split into
    file parts (bytes values) and data parts (everything else) so httpx encodes
    a proper multipart body and sets the boundary Content-Type itself."""
    if body_json is NOT_GIVEN:
        return {}
    if content_type.startswith("multipart/form-data") and isinstance(body_json, dict):
        files: list[tuple[str, Any]] = []

        def append(name: str, value: Any) -> None:
            if value is NOT_GIVEN:
                return
            if isinstance(value, (list, tuple)):
                for item in value:
                    append(name, item)
                return
            if isinstance(value, UploadFile):
                files.append((name, (value.filename, value.data, value.content_type)))
                return
            if isinstance(value, MultipartPart):
                files.append((name, (value.filename, value.data, value.content_type)))
                return
            if isinstance(value, (bytes, bytearray)):
                files.append((name, (name, bytes(value), "application/octet-stream")))
                return
            # HTTPX treats a file tuple with filename=None as a regular form
            # field. Keeping every part in this ordered list preserves repeated
            # scalar names and explicit empty strings without its Mapping-only
            # data type collapsing duplicates.
            files.append((name, (None, _wire_scalar(value))))

        for key, value in body_json.items():
            append(key, value)
        # httpx's MultipartStream is synchronous. Pre-render it once because
        # UploadFile stores bytes already, then both Client and AsyncClient can
        # send the exact same payload. Keep httpx as the boundary generator so
        # filenames, escaping, and per-part content types remain standards-
        # compliant instead of hand-building a boundary-less body.
        encoded = httpx.Request(
            "POST",
            "http://multipart.invalid",
            files=files or None,
        )
        payload = encoded.read()
        if headers is not None:
            boundary_type = encoded.headers.get("Content-Type")
            if boundary_type:
                headers["Content-Type"] = boundary_type
        return {"content": payload}
    return {"json": _wire_json(body_json)}


def _request_id(headers: httpx.Headers) -> str | None:
    for name in _REQUEST_ID_HEADERS:
        value = headers.get(name)
        if value:
            return value
    return None


def _should_retry_status(method: str, status: int, retry_on: tuple[int, ...]) -> bool:
    if status not in retry_on:
        return False
    if method in _IDEMPOTENT_METHODS:
        return True
    return status in _ALWAYS_RETRYABLE_STATUSES


def _compute_backoff(retry: RetryConfig, attempt: int, retry_after: str | None) -> float:
    if retry_after:
        try:
            seconds = float(retry_after)
            if seconds > 0:
                return min(seconds, retry.max_backoff_ms / 1000)
        except ValueError:
            try:
                target = parsedate_to_datetime(retry_after).timestamp()
                wait = max(target - time.time(), 0)
                return min(wait, retry.max_backoff_ms / 1000)
            except (TypeError, ValueError):
                pass
    base_ms = retry.backoff_ms * (2 ** (attempt - 1))
    jitter_ms = random.random() * retry.backoff_ms
    return min((base_ms + jitter_ms) / 1000, retry.max_backoff_ms / 1000)


def _parse_response_body(response: httpx.Response, decoder: str = "auto") -> Any:
    if decoder == "empty":
        return None
    if not response.content:
        if decoder == "json":
            raise ValueError("Expected a JSON response body but received zero bytes")
        return None
    content_type = response.headers.get("content-type", "")
    if decoder == "json" or "application/json" in content_type:
        return response.json()
    if decoder == "text" or content_type.startswith("text/"):
        return response.text
    return response.content


def _parse_error_body(response: httpx.Response) -> Any:
    """Preserve undecodable error payloads for ``SdkHttpError`` without displaying them."""
    if not response.content:
        return None
    content_type = response.headers.get("content-type", "").split(";", 1)[0].strip().lower()
    is_json = content_type == "application/json" or content_type.endswith("+json")
    if is_json or response.content.lstrip().startswith(b"{"):
        try:
            return response.json()
        except ValueError:
            return response.content
    if content_type.startswith("text/"):
        try:
            return response.content.decode("utf-8", errors="strict")
        except UnicodeDecodeError:
            return response.content
    return response.content


_UNSET = object()


def _call_policy(
    cfg: ClientConfig,
    method: str,
    idempotency_key: Any,
    options: RequestOptions,
) -> tuple[RetryConfig, float | None, str | None]:
    """Resolves one call's retry policy, timeout override, and idempotency key.
    A per-call option wins over the operation's own setting and the config."""
    if "idempotency_key" in options:
        idempotency_key = options["idempotency_key"]
    idem = cfg.idempotency
    if idempotency_key is _UNSET:
        key = uuid.uuid4().hex if idem.enabled and method in idem.methods else None
    elif idempotency_key is None:
        key = None
    else:
        key = str(idempotency_key)
    return options.get("retry", cfg.retry), options.get("timeout_s"), key


async def sdk_request(
    method: str,
    path: str,
    *,
    params: dict[str, Any] | None = None,
    json: Any = NOT_GIVEN,
    extra_headers: dict[str, str] | None = None,
    content_type: str = "application/json",
    operation_id: str = "",
    response_decoder: str = "json",
    config: ClientConfig | None = None,
    idempotency_key: Any = _UNSET,
    request_options: RequestOptions | None = None,
) -> SdkResponse[Any]:
    """Performs a typed HTTP request with retry, idempotency, and middleware.

    ``idempotency_key``: pass a ``str`` to override the auto-generated key,
    ``None`` to suppress idempotency for this call, or leave unset to honour
    the config policy. ``request_options`` applies over all of these.
    """
    cfg = config or _client_config
    method = method.upper()
    # Absolute URLs (used by url-style pagination follow links) bypass base_url.
    if path.startswith(("http://", "https://")):
        url = path
    else:
        url = f"{cfg.base_url or ''}{path}"
    clean_params = _strip_none(params) or {}
    # A path template can carry a literal query (OpenAI declares
    # `/responses?beta=true`). httpx REPLACES a URL's query when `params` is
    # passed, which would drop it, so fold it into the params the caller gave —
    # an explicit argument of the same name wins.
    if "?" in url:
        url, _, _literal_query = url.partition("?")
        clean_params = {
            **dict(parse_qsl(_literal_query, keep_blank_values=True)),
            **clean_params,
        }
    has_body = json is not NOT_GIVEN
    options: RequestOptions = request_options or {}
    # One idempotency key for the request — reused across all retries.
    retry, timeout_s, key = _call_policy(cfg, method, idempotency_key, options)
    idem = cfg.idempotency

    dispatch = _compose_middleware(cfg.middleware, _core_transport(cfg))

    last_error: BaseException | None = None
    for attempt in range(1, retry.max_attempts + 1):
        headers: dict[str, str] = {}
        extra_query: dict[str, str] = {}
        await _apply_auth(cfg, headers, extra_query, operation_id)
        if extra_headers:
            headers.update(extra_headers)
        headers.update(options.get("headers", {}))
        if has_body and not content_type.startswith("multipart/form-data"):
            # multipart: httpx sets Content-Type (with boundary) from files/data.
            headers["Content-Type"] = content_type
        if key is not None:
            headers[idem.header_name] = key
        merged_params = {**clean_params, **extra_query} if extra_query else clean_params

        request = SdkRequest(
            method=method,
            url=url,
            headers=headers,
            params=merged_params,
            body_json=json if has_body else None,
            content_type=content_type,
            response_decoder=response_decoder,
            operation_id=operation_id,
            attempt=attempt,
            timeout_s=timeout_s,
        )

        try:
            response = await dispatch(request)
        except httpx.TimeoutException as exc:
            last_error = exc
            if attempt < retry.max_attempts:
                await asyncio.sleep(_compute_backoff(retry, attempt, None))
                continue
            timeout_error = SdkTimeoutError(
                int((cfg.timeout_s if timeout_s is None else timeout_s) * 1000)
            )
            await _log_error(timeout_error, operation_id, method, path, cfg)
            add_breadcrumb(
                category="http", type="http", level="error", data={"method": method, "url": path}
            )
            raise timeout_error from exc
        except httpx.HTTPError as exc:
            last_error = exc
            if attempt < retry.max_attempts:
                await asyncio.sleep(_compute_backoff(retry, attempt, None))
                continue
            network_error = SdkNetworkError(exc)
            await _log_error(network_error, operation_id, method, path, cfg)
            add_breadcrumb(
                category="http", type="http", level="error", data={"method": method, "url": path}
            )
            raise network_error from exc

        if 200 <= response.status_code < 300:
            add_breadcrumb(
                category="http",
                type="http",
                level="info",
                data={"method": method, "url": path, "status_code": response.status_code},
            )
            if cfg.on_response is not None:
                cfg.on_response(response)
            return response

        if attempt < retry.max_attempts and _should_retry_status(
            method, response.status_code, retry.retry_on
        ):
            await asyncio.sleep(
                _compute_backoff(retry, attempt, response.headers.get("retry-after"))
            )
            continue

        http_error = SdkHttpError.for_status(
            status_code=response.status_code,
            status_text="",
            body=response.data,
            headers=response.headers,
            request_id=response.request_id,
        )
        await _log_error(http_error, operation_id, method, path, cfg)
        add_breadcrumb(
            category="http",
            type="http",
            level="error",
            data={"method": method, "url": path, "status_code": response.status_code},
        )
        raise http_error

    # Reachable only if retry.max_attempts is misconfigured to 0.
    raise SdkNetworkError(
        last_error or RuntimeError(f"Request '{operation_id}' produced no attempts")
    )


def _compose_middleware(
    stack: Sequence[Middleware],
    terminal: SdkNext,
) -> SdkNext:
    """Wraps ``stack`` around ``terminal`` so the first middleware is outermost."""
    if not stack:
        return terminal
    result: SdkNext = terminal
    for mw in reversed(stack):
        nxt = result

        async def _wrapper(req: SdkRequest, _mw=mw, _nxt=nxt) -> SdkResponse[Any]:
            return await _mw(req, _nxt)

        result = _wrapper
    return result


def _core_transport(cfg: ClientConfig) -> SdkNext:
    """Innermost dispatch: actual httpx call + envelope assembly. Non-2xx
    responses are returned as-is so middleware can inspect them; network
    failures propagate as exceptions for the retry loop to handle."""

    async def _send(req: SdkRequest) -> SdkResponse[Any]:
        started = time.monotonic()
        response = await cfg.client.request(
            req.method,
            _url_with_query(req.url, req.params),
            headers=req.headers,
            timeout=httpx.USE_CLIENT_DEFAULT if req.timeout_s is None else req.timeout_s,
            **_body_kwargs(req.content_type, req.body_json, req.headers),
        )
        latency_ms = int((time.monotonic() - started) * 1000)
        request_id = _request_id(response.headers)
        body = (
            _parse_response_body(response, req.response_decoder)
            if response.is_success
            else _parse_error_body(response)
        )
        resp_headers = {k.lower(): v for k, v in response.headers.items()}
        return SdkResponse(
            data=body,
            status_code=response.status_code,
            headers=resp_headers,
            request_id=request_id,
            latency_ms=latency_ms,
            attempt=req.attempt,
        )

    return _send


def sdk_request_sync(
    method: str,
    path: str,
    *,
    params: dict[str, Any] | None = None,
    json: Any = NOT_GIVEN,
    extra_headers: dict[str, str] | None = None,
    content_type: str = "application/json",
    operation_id: str = "",
    response_decoder: str = "json",
    config: ClientConfig | None = None,
    idempotency_key: Any = _UNSET,
    request_options: RequestOptions | None = None,
) -> SdkResponse[Any]:
    """Sync mirror of :func:`sdk_request`. Same retry, idempotency, and
    middleware semantics — uses ``httpx.Client`` and ``time.sleep`` instead of
    their async counterparts. Used by generated ``*_sync`` methods."""
    cfg = config or _client_config
    method = method.upper()
    if path.startswith(("http://", "https://")):
        url = path
    else:
        url = f"{cfg.base_url or ''}{path}"
    clean_params = _strip_none(params) or {}
    # A path template can carry a literal query (OpenAI declares
    # `/responses?beta=true`). httpx REPLACES a URL's query when `params` is
    # passed, which would drop it, so fold it into the params the caller gave —
    # an explicit argument of the same name wins.
    if "?" in url:
        url, _, _literal_query = url.partition("?")
        clean_params = {
            **dict(parse_qsl(_literal_query, keep_blank_values=True)),
            **clean_params,
        }
    has_body = json is not NOT_GIVEN
    options: RequestOptions = request_options or {}
    # One idempotency key for the request — reused across all retries.
    retry, timeout_s, key = _call_policy(cfg, method, idempotency_key, options)
    idem = cfg.idempotency

    dispatch = _compose_middleware_sync(cfg.sync_middleware, _core_transport_sync(cfg))

    last_error: BaseException | None = None
    for attempt in range(1, retry.max_attempts + 1):
        headers: dict[str, str] = {}
        extra_query: dict[str, str] = {}
        _apply_auth_sync(cfg, headers, extra_query, operation_id)
        if extra_headers:
            headers.update(extra_headers)
        headers.update(options.get("headers", {}))
        if has_body and not content_type.startswith("multipart/form-data"):
            # multipart: httpx sets Content-Type (with boundary) from files/data.
            headers["Content-Type"] = content_type
        if key is not None:
            headers[idem.header_name] = key
        merged_params = {**clean_params, **extra_query} if extra_query else clean_params

        request = SdkRequest(
            method=method,
            url=url,
            headers=headers,
            params=merged_params,
            body_json=json if has_body else None,
            content_type=content_type,
            response_decoder=response_decoder,
            operation_id=operation_id,
            attempt=attempt,
            timeout_s=timeout_s,
        )

        try:
            response = dispatch(request)
        except httpx.TimeoutException as exc:
            last_error = exc
            if attempt < retry.max_attempts:
                time.sleep(_compute_backoff(retry, attempt, None))
                continue
            timeout_error = SdkTimeoutError(
                int((cfg.timeout_s if timeout_s is None else timeout_s) * 1000)
            )
            _log_error_sync(timeout_error, operation_id, method, path, cfg)
            add_breadcrumb(
                category="http", type="http", level="error", data={"method": method, "url": path}
            )
            raise timeout_error from exc
        except httpx.HTTPError as exc:
            last_error = exc
            if attempt < retry.max_attempts:
                time.sleep(_compute_backoff(retry, attempt, None))
                continue
            network_error = SdkNetworkError(exc)
            _log_error_sync(network_error, operation_id, method, path, cfg)
            add_breadcrumb(
                category="http", type="http", level="error", data={"method": method, "url": path}
            )
            raise network_error from exc

        if 200 <= response.status_code < 300:
            add_breadcrumb(
                category="http",
                type="http",
                level="info",
                data={"method": method, "url": path, "status_code": response.status_code},
            )
            if cfg.on_response is not None:
                cfg.on_response(response)
            return response

        if attempt < retry.max_attempts and _should_retry_status(
            method, response.status_code, retry.retry_on
        ):
            time.sleep(_compute_backoff(retry, attempt, response.headers.get("retry-after")))
            continue

        http_error = SdkHttpError.for_status(
            status_code=response.status_code,
            status_text="",
            body=response.data,
            headers=response.headers,
            request_id=response.request_id,
        )
        _log_error_sync(http_error, operation_id, method, path, cfg)
        add_breadcrumb(
            category="http",
            type="http",
            level="error",
            data={"method": method, "url": path, "status_code": response.status_code},
        )
        raise http_error

    raise SdkNetworkError(
        last_error or RuntimeError(f"Request '{operation_id}' produced no attempts")
    )


def _compose_middleware_sync(
    stack: Sequence[SyncMiddleware],
    terminal: SyncSdkNext,
) -> SyncSdkNext:
    """Sync mirror of :func:`_compose_middleware`."""
    if not stack:
        return terminal
    result: SyncSdkNext = terminal
    for mw in reversed(stack):
        nxt = result

        def _wrapper(req: SdkRequest, _mw=mw, _nxt=nxt) -> SdkResponse[Any]:
            return _mw(req, _nxt)

        result = _wrapper
    return result


def _core_transport_sync(cfg: ClientConfig) -> SyncSdkNext:
    """Sync mirror of :func:`_core_transport`."""

    def _send(req: SdkRequest) -> SdkResponse[Any]:
        started = time.monotonic()
        response = cfg.sync_client.request(
            req.method,
            _url_with_query(req.url, req.params),
            headers=req.headers,
            timeout=httpx.USE_CLIENT_DEFAULT if req.timeout_s is None else req.timeout_s,
            **_body_kwargs(req.content_type, req.body_json, req.headers),
        )
        latency_ms = int((time.monotonic() - started) * 1000)
        request_id = _request_id(response.headers)
        body = (
            _parse_response_body(response, req.response_decoder)
            if response.is_success
            else _parse_error_body(response)
        )
        resp_headers = {k.lower(): v for k, v in response.headers.items()}
        return SdkResponse(
            data=body,
            status_code=response.status_code,
            headers=resp_headers,
            request_id=request_id,
            latency_ms=latency_ms,
            attempt=req.attempt,
        )

    return _send
