# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
import linecache
import traceback
import uuid

import httpx

from ._client_config import (
    ClientConfig,
    LoggingConfig,
    _breadcrumbs,
    _capture_context,
    _sanitize_pii,
)

_CONTEXT_LINES = 5


def _frame_in_app(filename: str) -> bool:
    """A frame is in-app unless it lives in the stdlib or an installed package."""
    if not filename:
        return False
    lowered = filename.replace("\\", "/").lower()
    for marker in ("/site-packages/", "/dist-packages/", "/lib/python", "<frozen", "<string"):
        if marker in lowered:
            return False
    return True


def _source_context(filename: str, lineno: int) -> dict:
    """A few source lines around `lineno`, so the dashboard can show the original
    code for languages that are not minified (no source maps required)."""
    if not filename or not lineno or lineno < 1:
        return {}
    try:
        lines = linecache.getlines(filename)
    except (OSError, ValueError):
        return {}
    if not lines or lineno > len(lines):
        return {}
    idx = lineno - 1
    ctx: dict = {"contextLine": lines[idx].rstrip("\n")}
    pre = [ln.rstrip("\n") for ln in lines[max(0, idx - _CONTEXT_LINES) : idx]]
    post = [ln.rstrip("\n") for ln in lines[idx + 1 : idx + 1 + _CONTEXT_LINES]]
    if pre:
        ctx["preContext"] = pre
    if post:
        ctx["postContext"] = post
    return ctx


def _build_frames(error: BaseException) -> list:
    """Structured stack frames with original-source context, innermost first
    (the throw site leads, matching the dashboard stack-trace convention)."""
    frames = []
    for summary in reversed(traceback.extract_tb(error.__traceback__)):
        frame: dict = {
            "function": summary.name,
            "filename": summary.filename,
            "lineno": summary.lineno,
            "inApp": _frame_in_app(summary.filename),
        }
        frame.update(_source_context(summary.filename, summary.lineno or 0))
        frames.append(frame)
    return frames


def _build_log_payload(
    error: BaseException,
    operation_id: str,
    method: str,
    path: str,
    logging: LoggingConfig,
) -> dict:
    """Shared enriched payload for the async and sync loggers. eventId lets the
    monitoring backend deduplicate retried deliveries; the rest are enrichment
    fields it understands (level, stack, user/tags, etc.)."""
    stack = "".join(traceback.format_exception(type(error), error, error.__traceback__))
    error_obj: dict = {
        "name": type(error).__name__,
        "message": str(error),
        "stack": stack,
    }
    # Structured frames carry original-source context so the dashboard shows your
    # code directly — Python is not minified, so no source maps are needed.
    frames = _build_frames(error)
    if frames:
        error_obj["frames"] = frames
    payload: dict = {
        "eventId": str(uuid.uuid4()),
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "level": "error",
        "operationId": operation_id,
        "method": method,
        "path": path,
        "error": error_obj,
    }
    status_code = getattr(error, "status_code", None)
    if status_code is not None:
        payload["statusCode"] = status_code
    request_id = getattr(error, "request_id", None)
    if request_id is not None:
        payload["requestId"] = request_id
    if logging.environment:
        payload["environment"] = logging.environment
    if logging.release:
        payload["release"] = logging.release
    if logging.tags:
        payload["tags"] = logging.tags
    # Personal data (user, runtime context, breadcrumbs) is only sent once the
    # consumer has granted consent — GDPR-safe by default.
    if logging.consent:
        if logging.user:
            payload["user"] = logging.user
        ctx = _capture_context()
        if ctx:
            payload["context"] = ctx
        if _breadcrumbs:
            payload["breadcrumbs"] = list(_breadcrumbs)
    return payload


def _log_headers(logging: LoggingConfig) -> dict:
    headers = {"Content-Type": "application/json"}
    if logging.api_key:
        headers["Authorization"] = f"Bearer {logging.api_key}"
    return headers


async def _log_error(
    error: BaseException,
    operation_id: str,
    method: str,
    path: str,
    config: ClientConfig,
) -> None:
    logging = config.logging
    if not logging or not logging.enabled or not logging.endpoint:
        return
    payload = _sanitize_pii(
        _build_log_payload(error, operation_id, method, path, logging),
        logging.filter_pii,
    )
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            await client.post(logging.endpoint, json=payload, headers=_log_headers(logging))
    except (httpx.HTTPError, OSError, ValueError):
        # Best-effort telemetry: delivery failures must not mask the
        # originating error, but the catch stays narrow enough to let a real
        # bug (e.g. TypeError in payload construction) surface.
        pass


def _log_error_sync(
    error: BaseException,
    operation_id: str,
    method: str,
    path: str,
    config: ClientConfig,
) -> None:
    """Sync mirror of :func:`_log_error`. Uses ``httpx.Client`` instead of the
    async client; same fire-and-forget semantics."""
    logging = config.logging
    if not logging or not logging.enabled or not logging.endpoint:
        return
    payload = _sanitize_pii(
        _build_log_payload(error, operation_id, method, path, logging),
        logging.filter_pii,
    )
    try:
        with httpx.Client(timeout=5.0) as client:
            client.post(logging.endpoint, json=payload, headers=_log_headers(logging))
    except (httpx.HTTPError, OSError, ValueError):
        # Best-effort telemetry: delivery failures must not mask the
        # originating error, but the catch stays narrow enough to let a real
        # bug (e.g. TypeError in payload construction) surface.
        pass
