# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import asyncio
import datetime
import json as _json
import platform
from collections.abc import Awaitable, Callable, Sequence
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any, Final, Generic, TypedDict, TypeVar
from urllib.parse import quote

import httpx

from .errors import SdkResponse

if TYPE_CHECKING:
    from typing_extensions import Self


_PageT = TypeVar("_PageT")
_ItemT = TypeVar("_ItemT")


TRANSPORT_ENGINE: Final[str] = "httpx"
TRANSPORT_IMPLEMENTATION: Final[str] = "httpx"


@dataclass(frozen=True)
class NotGiven:
    """Public sentinel type used to distinguish omission from explicit null."""


NOT_GIVEN: Final[NotGiven] = NotGiven()


@dataclass(frozen=True)
class SdkPage(Generic[_PageT, _ItemT]):
    """One typed response page from a paginated operation."""

    data: _PageT
    items: list[_ItemT]
    has_more: bool


@dataclass(frozen=True)
class UploadFile:
    data: bytes
    filename: str
    content_type: str = "application/octet-stream"


@dataclass(frozen=True)
class MultipartPart:
    data: bytes
    content_type: str
    filename: str | None = None


def multipart_json(value: Any, content_type: str = "application/json") -> MultipartPart:
    return MultipartPart(
        data=_json.dumps(_wire_json(value), ensure_ascii=False, separators=(",", ":")).encode(
            "utf-8"
        ),
        content_type=content_type,
    )


def omit_unset(values: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in values.items() if value is not NOT_GIVEN}


def encode_path_segment(value: Any) -> str:
    # A path array uses the default `simple` style: its members comma-joined.
    if isinstance(value, (list, tuple)):
        return quote(",".join(_wire_scalar(item) for item in value), safe="")
    return quote(_wire_scalar(value), safe="")


def _wire_scalar(value: Any) -> str:
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, bool):
        return "true" if value else "false"
    # datetime is a date subclass, so it must be checked first to preserve the
    # RFC 3339 time component and its required T separator.
    if isinstance(value, datetime.datetime):
        return value.isoformat()
    if isinstance(value, datetime.date):
        return value.isoformat()
    if isinstance(value, datetime.time):
        return value.isoformat()
    if isinstance(value, (dict, list)):
        return _json.dumps(_wire_json(value), ensure_ascii=False, separators=(",", ":"))
    if value is None:
        return "null"
    return str(value)


def _wire_json(value: Any) -> Any:
    """Recursively normalize values that Python's JSON encoder cannot send."""
    if isinstance(value, (datetime.datetime, datetime.date, datetime.time)):
        return _wire_scalar(value)
    if isinstance(value, dict):
        return {key: _wire_json(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_wire_json(item) for item in value]
    return value


def serialize_query(
    values: Sequence[tuple[str, Any, str, bool]],
) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for name, value, style, explode in values:
        if value is NOT_GIVEN or value is None:
            continue
        if isinstance(value, (list, tuple)):
            encoded = [_wire_scalar(item) for item in value]
            result[name] = encoded if style == "form" and explode else ",".join(encoded)
        else:
            result[name] = _wire_scalar(value)
    return result


def serialize_headers(values: dict[str, Any]) -> dict[str, str]:
    return {
        name: _wire_scalar(value)
        for name, value in values.items()
        if value is not NOT_GIVEN and value is not None
    }


@dataclass
class ClientAuthConfig:
    api_key_auth: str | None = None
    headers: dict[str, str] = field(default_factory=dict)


@dataclass
class LoggingConfig:
    # The endpoint/key/environment are baked from the dashboard monitoring config
    # at generation time, but logging is DISABLED at rest: nothing is reported
    # until the consumer opts in with ``set_logging_config(...)`` or by
    # constructing the client with ``logging=LoggingConfig(enabled=True)``.
    enabled: bool = False
    endpoint: str | None = None
    api_key: str | None = None
    # Enrichment forwarded with every logged event.
    environment: str | None = None
    release: str | None = None
    user: dict | None = None
    tags: dict | None = None
    # GDPR consent gate. When False (the default), the user, runtime context and
    # breadcrumbs are NOT sent — only the error and the operation. Call
    # set_logging_consent(True) once the consumer has approved tracking.
    consent: bool = False
    max_breadcrumbs: int = 30
    # Redact common credentials and direct identifiers before telemetry is sent.
    filter_pii: bool = True


@dataclass
class RetryConfig:
    max_attempts: int = 3
    retry_on: tuple[int, ...] = (408, 425, 429, 500, 502, 503, 504)
    backoff_ms: int = 500
    max_backoff_ms: int = 8000


@dataclass
class IdempotencyConfig:
    """Controls client-side Idempotency-Key generation, so a retried write is
    not executed twice server-side. Configured in the SDK Studio."""

    enabled: bool = True
    header_name: str = "Idempotency-Key"
    methods: tuple[str, ...] = ("POST", "PATCH")


class StreamRequestOptions(TypedDict, total=False):
    """Per-call options a streaming operation accepts as ``request_options``."""

    headers: dict[str, str]
    """Merged over the auth and operation headers for this call."""


class RequestOptions(StreamRequestOptions, total=False):
    """Per-call options every generated operation accepts as ``request_options``.
    Each one applies to that call only, over the client config."""

    idempotency_key: str | None
    """Replaces the generated Idempotency-Key; ``None`` sends none."""
    retry: RetryConfig
    """Replaces the client's retry policy."""
    timeout_s: float
    """Replaces the client's per-attempt timeout."""


@dataclass
class SdkRequest:
    """A single in-flight HTTP attempt as seen by middleware. Mutating
    ``headers`` or ``body_json`` in a middleware affects the request before it
    hits the wire. ``meta`` is a free-form dict middleware can use to share
    state across the chain."""

    method: str
    url: str
    headers: dict[str, str]
    params: dict[str, Any]
    body_json: Any
    content_type: str
    response_decoder: str
    operation_id: str
    attempt: int
    meta: dict[str, Any] = field(default_factory=dict)
    timeout_s: float | None = None


SdkNext = Callable[["SdkRequest"], Awaitable[SdkResponse[Any]]]
Middleware = Callable[["SdkRequest", SdkNext], Awaitable[SdkResponse[Any]]]
"""User-supplied async request interceptor. Runs once per HTTP attempt (so
retries pass through it N times). Useful for logging, tracing, caching, custom
auth, response transforms, etc. — without forking the generator.

Example:
    async def logger(req, nxt):
        resp = await nxt(req)
        print(f"{req.method} {req.url} -> {resp.status_code}")
        return resp

    configure_client(ClientConfig(middleware=[logger]))
"""

SyncSdkNext = Callable[["SdkRequest"], SdkResponse[Any]]
SyncMiddleware = Callable[["SdkRequest", SyncSdkNext], SdkResponse[Any]]
"""Sync counterpart of :class:`Middleware`, invoked by sync method variants
(:func:`sdk_request_sync` and the generated ``*_sync`` methods)."""


# POSTs/PATCHes only retry on the explicit "back off and try again" statuses.
_IDEMPOTENT_METHODS = frozenset({"GET", "HEAD", "PUT", "DELETE", "OPTIONS"})
_ALWAYS_RETRYABLE_STATUSES = frozenset({429, 503})
_REQUEST_ID_HEADERS = ("x-request-id", "openai-request-id", "x-amzn-requestid")
_DEFAULT_TIMEOUT_S = 30.0


class ClientConfig:
    def __init__(
        self,
        base_url: str | None = None,
        auth: ClientAuthConfig | None = None,
        logging: LoggingConfig | None = None,
        retry: RetryConfig | None = None,
        idempotency: IdempotencyConfig | None = None,
        timeout_s: float | None = None,
        on_response: Callable[[SdkResponse[Any]], None] | None = None,
        middleware: Sequence[Middleware] | None = None,
        sync_middleware: Sequence[SyncMiddleware] | None = None,
    ) -> None:
        self.base_url = base_url
        self.auth = auth
        self.logging = logging or LoggingConfig()
        self.retry = retry or RetryConfig()
        self.idempotency = idempotency or IdempotencyConfig()
        self.timeout_s = timeout_s if timeout_s is not None else _DEFAULT_TIMEOUT_S
        self.on_response = on_response
        # Middleware lists are replaced wholesale on configure_client(), not
        # appended. Callers wanting to extend should spread the existing list.
        self.middleware: tuple[Middleware, ...] = tuple(middleware or ())
        self.sync_middleware: tuple[SyncMiddleware, ...] = tuple(sync_middleware or ())
        self._client: httpx.AsyncClient | None = None
        # The loop the cached async client belongs to. An AsyncClient is bound
        # to its creating loop, so one cached across loops (a second
        # asyncio.run, or a per-test loop) raises "Event loop is closed" on the
        # next request.
        self._client_loop: asyncio.AbstractEventLoop | None = None
        self._sync_client: httpx.Client | None = None

    @property
    def client(self) -> httpx.AsyncClient:
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None
        # Tests and integrations may inject a ready-made AsyncClient. Bind an
        # unmarked injected client to its first use loop; clients created here
        # remain replaced when they belong to a different loop.
        if self._client is not None and self._client_loop is None:
            self._client_loop = loop
        if self._client is None or self._client_loop is not loop:
            self._client = httpx.AsyncClient(timeout=self.timeout_s)
            self._client_loop = loop
        return self._client

    @property
    def sync_client(self) -> httpx.Client:
        """Sync httpx client used by :func:`sdk_request_sync` and ``*_sync``
        generated methods. Lazily constructed and re-used across calls."""
        if self._sync_client is None:
            self._sync_client = httpx.Client(timeout=self.timeout_s)
        return self._sync_client

    async def aclose(self) -> None:
        if self._client is not None:
            await self._client.aclose()
            self._client = None
        # Best-effort sync close — safe to call from an async context because
        # httpx.Client.close() is non-blocking once requests have completed.
        if self._sync_client is not None:
            self._sync_client.close()
            self._sync_client = None

    def close(self) -> None:
        """Sync close — releases the sync httpx client. Use from non-async
        contexts; async callers should use :meth:`aclose` instead."""
        if self._sync_client is not None:
            self._sync_client.close()
            self._sync_client = None

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *_: object) -> None:
        await self.aclose()

    def __enter__(self) -> Self:
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    async def request(
        self,
        method: str,
        path: str,
        *,
        params: dict[str, Any] | None = None,
        json: Any = NOT_GIVEN,
        content_type: str = "application/json",
        operation_id: str = "",
        request_options: RequestOptions | None = None,
    ) -> SdkResponse[Any]:
        from ._client_transport import sdk_request

        return await sdk_request(
            method,
            path,
            params=params,
            json=json,
            content_type=content_type,
            operation_id=operation_id,
            config=self,
            request_options=request_options,
        )

    def request_sync(
        self,
        method: str,
        path: str,
        *,
        params: dict[str, Any] | None = None,
        json: Any = NOT_GIVEN,
        content_type: str = "application/json",
        operation_id: str = "",
        request_options: RequestOptions | None = None,
    ) -> SdkResponse[Any]:
        from ._client_transport import sdk_request_sync

        return sdk_request_sync(
            method,
            path,
            params=params,
            json=json,
            content_type=content_type,
            operation_id=operation_id,
            config=self,
            request_options=request_options,
        )


_client_config = ClientConfig(base_url="")


def configure_client(
    config: ClientConfig | None = None,
    *,
    base_url: str | None = None,
    auth: ClientAuthConfig | None = None,
) -> ClientConfig:
    """Configure the shared client.

    ``base_url`` are the convenience form shown by SDK Studio;
    callers that need the full surface can still pass a ``ClientConfig``.
    """
    if config is not None:
        if config.base_url is not None:
            _client_config.base_url = config.base_url
        if config.auth is not None:
            _client_config.auth = config.auth
        if config.logging is not None:
            _client_config.logging = config.logging
        if config.retry is not None:
            _client_config.retry = config.retry
        if config.idempotency is not None:
            _client_config.idempotency = config.idempotency
        if config.timeout_s is not None:
            _client_config.timeout_s = config.timeout_s
        if config.on_response is not None:
            _client_config.on_response = config.on_response
        if config.middleware:
            _client_config.middleware = config.middleware
        if config.sync_middleware:
            _client_config.sync_middleware = config.sync_middleware
    if base_url is not None:
        _client_config.base_url = base_url
    if auth is not None:
        _client_config.auth = auth

    return _client_config


def get_client_config() -> ClientConfig:
    return _client_config


# ── Breadcrumbs + consent-gated context ─────────────────────────────────────────
# The SDK keeps a rolling buffer of breadcrumbs (its own HTTP calls plus anything
# the app records via add_breadcrumb) and, once consent is granted, attaches the
# user + runtime context to each reported error.

_breadcrumbs: list[dict[str, object]] = []


def add_breadcrumb(
    message: str | None = None,
    category: str | None = None,
    level: str = "info",
    type: str = "default",
    data: dict | None = None,
) -> None:
    """Record a breadcrumb (navigation, log line, …) into the rolling buffer."""
    crumb: dict[str, object] = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "type": type,
        "category": category,
        "level": level,
    }
    if message is not None:
        crumb["message"] = message
    if data is not None:
        crumb["data"] = data
    _breadcrumbs.append(crumb)
    max_crumbs = (_client_config.logging.max_breadcrumbs if _client_config.logging else 30) or 30
    if len(_breadcrumbs) > max_crumbs:
        del _breadcrumbs[:-max_crumbs]


def clear_breadcrumbs() -> None:
    _breadcrumbs.clear()


def set_user(user: dict | None) -> None:
    """Set the user attached to reported errors (only sent once consent is granted)."""
    if _client_config.logging is None:
        _client_config.logging = LoggingConfig()
    _client_config.logging.user = user


def set_logging_consent(consent: bool) -> None:
    """Grant/revoke GDPR consent for sending the user + runtime context + breadcrumbs."""
    if _client_config.logging is None:
        _client_config.logging = LoggingConfig()
    _client_config.logging.consent = consent


def set_logging_config(config: LoggingConfig | None = None, **fields) -> LoggingConfig:
    """Turn SDK logging on and configure it in one call.

    Logging is OFF by default — this SDK reports nothing until you ask it to.
    There are exactly two ways to turn it on::

        configure_client(logging=LoggingConfig(enabled=True))    # at init
        set_logging_config(environment="production")             # any time after

    Reports go to the endpoint this build was generated with, or to the
    ``endpoint`` you pass; with neither, nothing is sent. Every form below opts in::

        set_logging_config()
        set_logging_config(environment="production")
        set_logging_config(LoggingConfig(environment="production"))

    Pass ``enabled=False`` to turn logging back off.
    """
    if _client_config.logging is None:
        _client_config.logging = LoggingConfig()
    current = _client_config.logging
    if config is not None:
        # `enabled` on the passed object is deliberately ignored: it defaults to
        # False (logging is opt-in), so honouring it would make the obvious
        # set_logging_config(LoggingConfig(environment=...)) a silent no-op.
        # Calling this function IS the opt-in; use enabled=False to turn it off.
        for key, value in vars(config).items():
            if key != "enabled":
                setattr(current, key, value)
    current.enabled = True
    # Keywords are applied last, so an explicit enabled=False still wins.
    for key, value in fields.items():
        if not hasattr(current, key):
            raise TypeError(f"LoggingConfig has no field {key!r}")
        setattr(current, key, value)
    return current


def _capture_context() -> dict:
    """Server-side runtime context (no browser device/page data)."""
    try:
        return {
            "runtime": {
                "name": "python",
                "version": platform.python_version(),
                "platform": platform.platform(),
            }
        }
    except (OSError, ValueError):
        return {}


_PII_KEYS = frozenset(
    [
        "authorization",
        "cookie",
        "set_cookie",
        "setcookie",
        "password",
        "passcode",
        "secret",
        "token",
        "api_key",
        "apikey",
        "access_token",
        "accesstoken",
        "refresh_token",
        "refreshtoken",
        "client_secret",
        "clientsecret",
        "email",
        "email_address",
        "emailaddress",
        "phone",
        "phone_number",
        "phonenumber",
        "address",
        "street_address",
        "streetaddress",
        "street",
        "city",
        "postal_code",
        "postalcode",
        "zip_code",
        "zipcode",
        "first_name",
        "firstname",
        "last_name",
        "lastname",
        "full_name",
        "fullname",
        "username",
        "user_name",
        "ip",
        "ip_address",
        "ipaddress",
        "user_agent",
        "useragent",
        "referrer",
        "url",
        "uri",
        "query",
        "latitude",
        "longitude",
        "ssn",
        "social_security_number",
        "socialsecuritynumber",
        "tax_id",
        "taxid",
        "national_id",
        "nationalid",
        "passport_number",
        "passportnumber",
        "date_of_birth",
        "dateofbirth",
        "birth_date",
        "birthdate",
        "headers",
        "body",
        "request_headers",
        "requestheaders",
        "request_body",
        "requestbody",
    ]
)
# Word runs matched anywhere inside a key (`billingEmail`, `stripe_secret_key`).
_PII_SEGMENTS = (
    "_password_",
    "_passwd_",
    "_passphrase_",
    "_secret_",
    "_token_",
    "_api_key_",
    "_access_token_",
    "_refresh_token_",
    "_client_secret_",
    "_authorization_",
    "_cookie_",
    "_set_cookie_",
    "_credential_",
    "_private_key_",
    "_access_key_",
    "_session_id_",
    "_card_number_",
    "_credit_card_",
    "_cvv_",
    "_cvc_",
    "_email_",
    "_email_address_",
    "_phone_",
    "_phone_number_",
    "_address_",
    "_street_address_",
    "_postal_code_",
    "_zip_code_",
    "_first_name_",
    "_last_name_",
    "_full_name_",
    "_user_name_",
    "_user_agent_",
    "_ssn_",
    "_social_security_number_",
    "_tax_id_",
    "_national_id_",
    "_passport_number_",
    "_passport_",
    "_date_of_birth_",
    "_birth_date_",
    "_birthdate_",
    "_dob_",
)
_PII_REDACTION_MARKER = "[REDACTED]"


def _normalize_pii_key(key: object) -> str:
    """`stripeSecretKey`, `API-Key` and `first name` become `stripe_secret_key`, `api_key`, `first_name`."""
    out: list[str] = []
    previous = ""
    for char in str(key):
        if char.isupper() and (previous.islower() or previous.isdigit()):
            out.append("_")
        out.append(char.lower() if char.isalnum() else "_")
        previous = char
    return "".join(out)


def _is_pii_key(key: object) -> bool:
    normalized = _normalize_pii_key(key)
    if normalized in _PII_KEYS:
        return True
    padded = f"_{normalized}_"
    return any(segment in padded for segment in _PII_SEGMENTS)


def _sanitize_pii(value: Any, enabled: bool) -> Any:
    """Recursively redact known credential and direct-identifier fields."""
    if not enabled:
        return value
    if isinstance(value, dict):
        return {
            key: _PII_REDACTION_MARKER if _is_pii_key(key) else _sanitize_pii(item, enabled)
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [_sanitize_pii(item, enabled) for item in value]
    if isinstance(value, tuple):
        return tuple(_sanitize_pii(item, enabled) for item in value)
    return value
