# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import UnionType
from typing import Any, Generic, TypeVar, get_args, overload

from pydantic import TypeAdapter, ValidationError

T = TypeVar("T")
M = TypeVar("M")


@dataclass
class SdkResponse(Generic[T]):
    """Envelope returned by the low-level request layer.

    High-level endpoint methods unwrap ``.data`` automatically; callers that
    need the metadata use the request layer directly.
    """

    data: T
    status_code: int
    headers: Mapping[str, str]
    request_id: str | None
    latency_ms: int
    attempt: int


class SdkError(Exception):
    """Base class for every error the SDK may raise."""


class SdkStreamParseError(SdkError):
    """Raised when a typed streaming payload is not valid JSON."""

    def __init__(self, payload: str, cause: BaseException):
        super().__init__("Unable to parse typed streaming payload")
        self.payload = payload
        self.cause = cause


class SdkAuthError(SdkError):
    """Raised when the selected authentication mode cannot call an operation."""

    def __init__(self, operation_id: str, preference: str, message: str):
        super().__init__(message)
        self.operation_id = operation_id
        self.preference = preference
        self.message = message


class SdkAuthProviderError(SdkError):
    """Raised when an OAuth 2 token provider cannot supply a usable access token."""

    def __init__(
        self,
        operation_id: str,
        scheme: str,
        scopes: tuple[str, ...],
        message: str,
        cause: BaseException | None = None,
    ):
        super().__init__(message)
        self.operation_id = operation_id
        self.scheme = scheme
        self.scopes = scopes
        self.message = message
        self.cause = cause


class SdkValidationError(SdkError):
    """Raised when a method argument fails an OpenAPI constraint pre-flight."""

    def __init__(self, field: str, code: str, message: str, meta: dict | None = None):
        super().__init__(message)
        self.field = field
        self.code = code
        self.meta = meta or {}


_MAX_ERROR_DETAIL_LENGTH = 512


def _error_detail(body: object, headers: Mapping[str, str]) -> str | None:
    """Return a bounded, human-readable API error detail without serializing bodies."""
    candidate: str | None = None
    content_type = next(
        (
            value.split(";", 1)[0].strip().lower()
            for key, value in headers.items()
            if key.lower() == "content-type"
        ),
        "",
    )
    is_json = content_type == "application/json" or content_type.endswith("+json")
    if isinstance(body, str):
        if not is_json and (not content_type or content_type.startswith("text/")):
            candidate = body
    elif isinstance(body, Mapping):
        for key in ("message", "detail"):
            value = body.get(key)
            if isinstance(value, str):
                candidate = value
                break
        if candidate is None:
            error = body.get("error")
            if isinstance(error, Mapping):
                for key in ("message", "detail"):
                    value = error.get(key)
                    if isinstance(value, str):
                        candidate = value
                        break
            elif isinstance(error, str):
                candidate = error

    if candidate is None:
        return None
    normalized = " ".join(candidate.split())
    if not normalized or not normalized.isprintable():
        return None
    if len(normalized) <= _MAX_ERROR_DETAIL_LENGTH:
        return normalized
    return f"{normalized[:_MAX_ERROR_DETAIL_LENGTH].rstrip()}…"


class SdkHttpError(SdkError):
    """Raised for any non-2xx HTTP response."""

    def __init__(
        self,
        status_code: int,
        status_text: str,
        body: Any,
        headers: Mapping[str, str],
        request_id: str | None = None,
    ):
        message = f"HTTP {status_code}"
        if status_text:
            message = f"{message} {status_text}"
        detail = _error_detail(body, headers)
        if detail:
            message = f"{message}: {detail}"
        super().__init__(message)
        self.status_code = status_code
        self.status_text = status_text
        self.body = body
        self.headers = headers
        self.request_id = request_id

    @classmethod
    def for_status(
        cls,
        status_code: int,
        status_text: str,
        body: Any,
        headers: Mapping[str, str],
        request_id: str | None = None,
    ) -> SdkHttpError:
        """Builds the status-specific subclass, or the base class for other statuses."""
        error_class = (
            SdkInternalServerError
            if status_code >= 500
            else _STATUS_ERRORS.get(status_code, SdkHttpError)
        )
        return error_class(status_code, status_text, body, headers, request_id)

    @overload
    def decode_body(self, model: type[M]) -> M: ...

    @overload
    def decode_body(self, model: UnionType) -> object: ...

    def decode_body(self, model: type[M] | UnionType) -> M | object:
        """Decodes the body into the model the API declares for this error.

        Validation matches a success response: a body that does not fit the
        model raises pydantic's ``ValidationError``, and ``body`` keeps the raw data.
        An operation's ``<Operation>Error`` alias decodes to the first of its
        models the body fits; narrow that result with ``isinstance``.
        """
        if isinstance(model, UnionType):
            *candidates, last = get_args(model)
            for candidate in candidates:
                try:
                    return self.decode_body(candidate)
                except (ValidationError, SdkValidationError):
                    continue
            return self.decode_body(last)
        from . import types as _types

        adapter = TypeAdapter(model)
        if not adapter.pydantic_complete:
            adapter.rebuild(_types_namespace=vars(_types))
        if isinstance(self.body, (str, bytes)):
            return adapter.validate_json(self.body)
        return adapter.validate_python(self.body)


class SdkBadRequestError(SdkHttpError):
    """Raised for an HTTP 400 response."""


class SdkUnauthorizedError(SdkHttpError):
    """Raised for an HTTP 401 response."""


class SdkPermissionDeniedError(SdkHttpError):
    """Raised for an HTTP 403 response."""


class SdkNotFoundError(SdkHttpError):
    """Raised for an HTTP 404 response."""


class SdkConflictError(SdkHttpError):
    """Raised for an HTTP 409 response."""


class SdkUnprocessableEntityError(SdkHttpError):
    """Raised for an HTTP 422 response."""


class SdkRateLimitError(SdkHttpError):
    """Raised for an HTTP 429 response."""


class SdkInternalServerError(SdkHttpError):
    """Raised for any HTTP 5xx response."""


_STATUS_ERRORS: dict[int, type[SdkHttpError]] = {
    400: SdkBadRequestError,
    401: SdkUnauthorizedError,
    403: SdkPermissionDeniedError,
    404: SdkNotFoundError,
    409: SdkConflictError,
    422: SdkUnprocessableEntityError,
    429: SdkRateLimitError,
}


class SdkNetworkError(SdkError):
    """Raised for connection / DNS / socket failures."""

    def __init__(self, cause: BaseException, request_id: str | None = None):
        super().__init__(str(cause))
        self.cause = cause
        self.request_id = request_id


class SdkTimeoutError(SdkError):
    """Raised when a request exceeds its configured timeout."""

    def __init__(self, elapsed_ms: int, request_id: str | None = None):
        super().__init__(f"Request timed out after {elapsed_ms}ms")
        self.elapsed_ms = elapsed_ms
        self.request_id = request_id
