# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import fields, is_dataclass
from typing import Any, cast

from .errors import SdkValidationError
from .types import (
    ModelsDiagnostics,
    ModelsHeartbeat,
    ModelsSummary,
    ModelsSummaryItem,
    V1AllTimeData,
    V1AllTimeRange,
    V1AllTimeViewModel,
    V1BadgeData,
    V1HeartbeatEntry,
    V1HeartbeatsResult,
    V1LeadersCurrentUser,
    V1LeadersEntry,
    V1LeadersLanguage,
    V1LeadersRange,
    V1LeadersRunningTotal,
    V1LeadersViewModel,
    V1Project,
    V1ProjectsViewModel,
    V1ProjectViewModel,
    V1StatsData,
    V1StatsViewModel,
    V1StatusBarViewModel,
    V1SummariesCumulativeTotal,
    V1SummariesDailyAverage,
    V1SummariesData,
    V1SummariesEntry,
    V1SummariesGrandTotal,
    V1SummariesRange,
    V1SummariesViewModel,
    V1User,
    V1UserAgentEntry,
    V1UserAgentsViewModel,
    V1UserViewModel,
)
from .validation import validate_date
from .wire import to_wire

MODEL_CONSTRUCTION_STYLE = "pydantic"

_SCHEMAS: dict[str, Any] = {
    "ModelsDiagnostics": {
        "type": "object",
        "properties": {
            "architecture": {"python": "architecture", "type": "string"},
            "cli_version": {"python": "cli_version", "type": "string"},
            "id": {"python": "id", "type": "integer"},
            "logs": {"python": "logs", "type": "string"},
            "platform": {"python": "platform", "type": "string"},
            "plugin": {"python": "plugin", "type": "string"},
            "stacktrace": {"python": "stacktrace", "type": "string"},
        },
    },
    "ModelsHeartbeat": {
        "type": "object",
        "properties": {
            "ai_input_tokens": {"python": "ai_input_tokens", "type": "integer"},
            "ai_line_changes": {"python": "ai_line_changes", "type": "integer"},
            "ai_output_tokens": {"python": "ai_output_tokens", "type": "integer"},
            "ai_prompt_length": {"python": "ai_prompt_length", "type": "integer"},
            "ai_session": {"python": "ai_session", "type": "string"},
            "branch": {"python": "branch", "type": "string"},
            "category": {"python": "category", "type": "string"},
            "created_at": {"python": "created_at", "type": "number"},
            "cursorpos": {"python": "cursorpos", "type": "integer"},
            "editor": {"python": "editor", "type": "string"},
            "entity": {"python": "entity", "type": "string"},
            "human_line_changes": {"python": "human_line_changes", "type": "integer"},
            "is_write": {"python": "is_write", "type": "boolean"},
            "language": {"python": "language", "type": "string"},
            "line_additions": {"python": "line_additions", "type": "integer"},
            "line_deletions": {"python": "line_deletions", "type": "integer"},
            "lineno": {"python": "lineno", "type": "integer"},
            "lines": {"python": "lines", "type": "integer"},
            "machine": {"python": "machine", "type": "string"},
            "operating_system": {"python": "operating_system", "type": "string"},
            "project": {"python": "project", "type": "string"},
            "project_root_count": {"python": "project_root_count", "type": "integer"},
            "time": {"python": "time", "type": "number"},
            "type": {"python": "type", "type": "string"},
            "user_agent": {"python": "user_agent", "type": "string"},
        },
    },
    "ModelsSummary": {
        "type": "object",
        "properties": {
            "branches": {
                "python": "branches",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "categories": {
                "python": "categories",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "editors": {
                "python": "editors",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "entities": {
                "python": "entities",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "from": {"python": "from_", "type": "string", "format": "date"},
            "labels": {"python": "labels", "type": "array", "items": {"ref": "ModelsSummaryItem"}},
            "languages": {
                "python": "languages",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "machines": {
                "python": "machines",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "operating_systems": {
                "python": "operating_systems",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "projects": {
                "python": "projects",
                "type": "array",
                "items": {"ref": "ModelsSummaryItem"},
            },
            "to": {"python": "to", "type": "string", "format": "date"},
            "user_id": {"python": "user_id", "type": "string"},
        },
    },
    "ModelsSummaryItem": {
        "type": "object",
        "properties": {
            "key": {"python": "key", "type": "string"},
            "total": {"python": "total", "type": "integer"},
        },
    },
    "V1AllTimeData": {
        "type": "object",
        "properties": {
            "is_up_to_date": {"python": "is_up_to_date", "type": "boolean"},
            "range": {"python": "range", "ref": "V1AllTimeRange"},
            "text": {"python": "text", "type": "string"},
            "total_seconds": {"python": "total_seconds", "type": "number"},
        },
    },
    "V1AllTimeRange": {
        "type": "object",
        "properties": {
            "end": {"python": "end", "type": "string"},
            "end_date": {"python": "end_date", "type": "string"},
            "start": {"python": "start", "type": "string"},
            "start_date": {"python": "start_date", "type": "string"},
            "timezone": {"python": "timezone", "type": "string"},
        },
    },
    "V1AllTimeViewModel": {
        "type": "object",
        "properties": {"data": {"python": "data", "ref": "V1AllTimeData"}},
    },
    "V1BadgeData": {
        "type": "object",
        "properties": {
            "color": {"python": "color", "type": "string"},
            "label": {"python": "label", "type": "string"},
            "message": {"python": "message", "type": "string"},
            "schemaVersion": {"python": "schema_version", "type": "integer"},
        },
    },
    "V1HeartbeatEntry": {
        "type": "object",
        "properties": {
            "ai_input_tokens": {"python": "ai_input_tokens", "type": "integer"},
            "ai_line_changes": {"python": "ai_line_changes", "type": "integer"},
            "ai_output_tokens": {"python": "ai_output_tokens", "type": "integer"},
            "ai_prompt_length": {"python": "ai_prompt_length", "type": "integer"},
            "ai_session": {"python": "ai_session", "type": "string"},
            "branch": {"python": "branch", "type": "string"},
            "category": {"python": "category", "type": "string"},
            "created_at": {"python": "created_at", "type": "string"},
            "cursorpos": {"python": "cursorpos", "type": "integer"},
            "entity": {"python": "entity", "type": "string"},
            "human_line_changes": {"python": "human_line_changes", "type": "integer"},
            "id": {"python": "id", "type": "string"},
            "is_write": {"python": "is_write", "type": "boolean"},
            "language": {"python": "language", "type": "string"},
            "line_additions": {"python": "line_additions", "type": "integer"},
            "line_deletions": {"python": "line_deletions", "type": "integer"},
            "lineno": {"python": "lineno", "type": "integer"},
            "lines": {"python": "lines", "type": "integer"},
            "machine_name_id": {"python": "machine_name_id", "type": "string"},
            "project": {"python": "project", "type": "string"},
            "time": {"python": "time", "type": "number"},
            "type": {"python": "type", "type": "string"},
            "user_agent_id": {"python": "user_agent_id", "type": "string"},
            "user_id": {"python": "user_id", "type": "string"},
        },
    },
    "V1HeartbeatsResult": {
        "type": "object",
        "properties": {
            "data": {"python": "data", "type": "array", "items": {"ref": "V1HeartbeatEntry"}},
            "end": {"python": "end", "type": "string"},
            "start": {"python": "start", "type": "string"},
            "timezone": {"python": "timezone", "type": "string"},
        },
    },
    "V1LeadersCurrentUser": {
        "type": "object",
        "properties": {
            "page": {"python": "page", "type": "integer"},
            "rank": {"python": "rank", "type": "integer"},
            "user": {"python": "user", "ref": "V1User"},
        },
    },
    "V1LeadersEntry": {
        "type": "object",
        "properties": {
            "rank": {"python": "rank", "type": "integer"},
            "running_total": {"python": "running_total", "ref": "V1LeadersRunningTotal"},
            "user": {"python": "user", "ref": "V1User"},
        },
    },
    "V1LeadersLanguage": {
        "type": "object",
        "properties": {
            "name": {"python": "name", "type": "string"},
            "total_seconds": {"python": "total_seconds", "type": "number"},
        },
    },
    "V1LeadersRange": {
        "type": "object",
        "properties": {
            "end_date": {"python": "end_date", "type": "string"},
            "end_text": {"python": "end_text", "type": "string"},
            "name": {"python": "name", "type": "string"},
            "start_date": {"python": "start_date", "type": "string"},
            "start_text": {"python": "start_text", "type": "string"},
            "text": {"python": "text", "type": "string"},
        },
    },
    "V1LeadersRunningTotal": {
        "type": "object",
        "properties": {
            "daily_average": {"python": "daily_average", "type": "number"},
            "human_readable_daily_average": {
                "python": "human_readable_daily_average",
                "type": "string",
            },
            "human_readable_total": {"python": "human_readable_total", "type": "string"},
            "languages": {
                "python": "languages",
                "type": "array",
                "items": {"ref": "V1LeadersLanguage"},
            },
            "total_seconds": {"python": "total_seconds", "type": "number"},
        },
    },
    "V1LeadersViewModel": {
        "type": "object",
        "properties": {
            "current_user": {"python": "current_user", "ref": "V1LeadersCurrentUser"},
            "data": {"python": "data", "type": "array", "items": {"ref": "V1LeadersEntry"}},
            "language": {"python": "language", "type": "string"},
            "page": {"python": "page", "type": "integer"},
            "range": {"python": "range", "ref": "V1LeadersRange"},
            "total_pages": {"python": "total_pages", "type": "integer"},
        },
    },
    "V1Project": {
        "type": "object",
        "properties": {
            "created_at": {"python": "created_at", "type": "string"},
            "human_readable_last_heartbeat_at": {
                "python": "human_readable_last_heartbeat_at",
                "type": "string",
            },
            "id": {"python": "id", "type": "string"},
            "last_heartbeat_at": {"python": "last_heartbeat_at", "type": "string"},
            "name": {"python": "name", "type": "string"},
            "urlencoded_name": {"python": "urlencoded_name", "type": "string"},
        },
    },
    "V1ProjectViewModel": {
        "type": "object",
        "properties": {"data": {"python": "data", "ref": "V1Project"}},
    },
    "V1ProjectsViewModel": {
        "type": "object",
        "properties": {"data": {"python": "data", "type": "array", "items": {"ref": "V1Project"}}},
    },
    "V1StatsData": {
        "type": "object",
        "properties": {
            "branches": {
                "python": "branches",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "categories": {
                "python": "categories",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "daily_average": {"python": "daily_average", "type": "number"},
            "days_including_holidays": {"python": "days_including_holidays", "type": "integer"},
            "editors": {"python": "editors", "type": "array", "items": {"ref": "V1SummariesEntry"}},
            "end": {"python": "end", "type": "string"},
            "human_readable_daily_average": {
                "python": "human_readable_daily_average",
                "type": "string",
            },
            "human_readable_range": {"python": "human_readable_range", "type": "string"},
            "human_readable_total": {"python": "human_readable_total", "type": "string"},
            "is_coding_activity_visible": {
                "python": "is_coding_activity_visible",
                "type": "boolean",
            },
            "is_other_usage_visible": {"python": "is_other_usage_visible", "type": "boolean"},
            "languages": {
                "python": "languages",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "machines": {
                "python": "machines",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "operating_systems": {
                "python": "operating_systems",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "projects": {
                "python": "projects",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "range": {"python": "range", "type": "string"},
            "start": {"python": "start", "type": "string"},
            "status": {"python": "status", "type": "string"},
            "timezone": {"python": "timezone", "type": "string"},
            "total_seconds": {"python": "total_seconds", "type": "number"},
            "user_id": {"python": "user_id", "type": "string"},
            "username": {"python": "username", "type": "string"},
        },
    },
    "V1StatsViewModel": {
        "type": "object",
        "properties": {"data": {"python": "data", "ref": "V1StatsData"}},
    },
    "V1StatusBarViewModel": {
        "type": "object",
        "properties": {
            "cached_at": {"python": "cached_at", "type": "string"},
            "data": {"python": "data", "ref": "V1SummariesData"},
        },
    },
    "V1SummariesCumulativeTotal": {
        "type": "object",
        "properties": {
            "decimal": {"python": "decimal", "type": "string"},
            "digital": {"python": "digital", "type": "string"},
            "seconds": {"python": "seconds", "type": "number"},
            "text": {"python": "text", "type": "string"},
        },
    },
    "V1SummariesDailyAverage": {
        "type": "object",
        "properties": {
            "days_including_holidays": {"python": "days_including_holidays", "type": "integer"},
            "days_minus_holidays": {"python": "days_minus_holidays", "type": "integer"},
            "holidays": {"python": "holidays", "type": "integer"},
            "seconds": {"python": "seconds", "type": "integer"},
            "seconds_including_other_language": {
                "python": "seconds_including_other_language",
                "type": "integer",
            },
            "text": {"python": "text", "type": "string"},
            "text_including_other_language": {
                "python": "text_including_other_language",
                "type": "string",
            },
        },
    },
    "V1SummariesData": {
        "type": "object",
        "properties": {
            "branches": {
                "python": "branches",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "categories": {
                "python": "categories",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "dependencies": {
                "python": "dependencies",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "editors": {"python": "editors", "type": "array", "items": {"ref": "V1SummariesEntry"}},
            "entities": {
                "python": "entities",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "grand_total": {"python": "grand_total", "ref": "V1SummariesGrandTotal"},
            "languages": {
                "python": "languages",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "machines": {
                "python": "machines",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "operating_systems": {
                "python": "operating_systems",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "projects": {
                "python": "projects",
                "type": "array",
                "items": {"ref": "V1SummariesEntry"},
            },
            "range": {"python": "range", "ref": "V1SummariesRange"},
        },
    },
    "V1SummariesEntry": {
        "type": "object",
        "properties": {
            "digital": {"python": "digital", "type": "string"},
            "hours": {"python": "hours", "type": "integer"},
            "minutes": {"python": "minutes", "type": "integer"},
            "name": {"python": "name", "type": "string"},
            "percent": {"python": "percent", "type": "number"},
            "seconds": {"python": "seconds", "type": "integer"},
            "text": {"python": "text", "type": "string"},
            "total_seconds": {"python": "total_seconds", "type": "number"},
        },
    },
    "V1SummariesGrandTotal": {
        "type": "object",
        "properties": {
            "digital": {"python": "digital", "type": "string"},
            "hours": {"python": "hours", "type": "integer"},
            "minutes": {"python": "minutes", "type": "integer"},
            "text": {"python": "text", "type": "string"},
            "total_seconds": {"python": "total_seconds", "type": "number"},
        },
    },
    "V1SummariesRange": {
        "type": "object",
        "properties": {
            "date": {"python": "date", "type": "string"},
            "end": {"python": "end", "type": "string"},
            "start": {"python": "start", "type": "string"},
            "text": {"python": "text", "type": "string"},
            "timezone": {"python": "timezone", "type": "string"},
        },
    },
    "V1SummariesViewModel": {
        "type": "object",
        "properties": {
            "cumulative_total": {"python": "cumulative_total", "ref": "V1SummariesCumulativeTotal"},
            "daily_average": {"python": "daily_average", "ref": "V1SummariesDailyAverage"},
            "data": {"python": "data", "type": "array", "items": {"ref": "V1SummariesData"}},
            "end": {"python": "end", "type": "string"},
            "start": {"python": "start", "type": "string"},
        },
    },
    "V1User": {
        "type": "object",
        "properties": {
            "created_at": {"python": "created_at", "type": "string"},
            "display_name": {"python": "display_name", "type": "string"},
            "email": {"python": "email", "type": "string"},
            "full_name": {"python": "full_name", "type": "string"},
            "id": {"python": "id", "type": "string"},
            "is_email_confirmed": {"python": "is_email_confirmed", "type": "boolean"},
            "is_email_public": {"python": "is_email_public", "type": "boolean"},
            "last_heartbeat_at": {"python": "last_heartbeat_at", "type": "string"},
            "last_plugin_name": {"python": "last_plugin_name", "type": "string"},
            "last_project": {"python": "last_project", "type": "string"},
            "modified_at": {"python": "modified_at", "type": "string"},
            "photo": {"python": "photo", "type": "string"},
            "timezone": {"python": "timezone", "type": "string"},
            "username": {"python": "username", "type": "string"},
            "website": {"python": "website", "type": "string"},
        },
    },
    "V1UserAgentEntry": {
        "type": "object",
        "properties": {
            "editor": {"python": "editor", "type": "string"},
            "first_seen": {"python": "first_seen", "type": "string"},
            "id": {"python": "id", "type": "string"},
            "is_browser_extension": {"python": "is_browser_extension", "type": "boolean"},
            "is_desktop_app": {"python": "is_desktop_app", "type": "boolean"},
            "last_seen": {"python": "last_seen", "type": "string"},
            "os": {"python": "os", "type": "string"},
            "value": {"python": "value", "type": "string"},
            "version": {"python": "version", "type": "string"},
        },
    },
    "V1UserAgentsViewModel": {
        "type": "object",
        "properties": {
            "data": {"python": "data", "type": "array", "items": {"ref": "V1UserAgentEntry"}},
            "total_pages": {"python": "total_pages", "type": "integer"},
        },
    },
    "V1UserViewModel": {
        "type": "object",
        "properties": {"data": {"python": "data", "ref": "V1User"}},
    },
}
_MODEL_TYPES: dict[str, type[Any]] = {
    "ModelsDiagnostics": ModelsDiagnostics,
    "ModelsHeartbeat": ModelsHeartbeat,
    "ModelsSummary": ModelsSummary,
    "ModelsSummaryItem": ModelsSummaryItem,
    "V1AllTimeData": V1AllTimeData,
    "V1AllTimeRange": V1AllTimeRange,
    "V1AllTimeViewModel": V1AllTimeViewModel,
    "V1BadgeData": V1BadgeData,
    "V1HeartbeatEntry": V1HeartbeatEntry,
    "V1HeartbeatsResult": V1HeartbeatsResult,
    "V1LeadersCurrentUser": V1LeadersCurrentUser,
    "V1LeadersEntry": V1LeadersEntry,
    "V1LeadersLanguage": V1LeadersLanguage,
    "V1LeadersRange": V1LeadersRange,
    "V1LeadersRunningTotal": V1LeadersRunningTotal,
    "V1LeadersViewModel": V1LeadersViewModel,
    "V1Project": V1Project,
    "V1ProjectViewModel": V1ProjectViewModel,
    "V1ProjectsViewModel": V1ProjectsViewModel,
    "V1StatsData": V1StatsData,
    "V1StatsViewModel": V1StatsViewModel,
    "V1StatusBarViewModel": V1StatusBarViewModel,
    "V1SummariesCumulativeTotal": V1SummariesCumulativeTotal,
    "V1SummariesDailyAverage": V1SummariesDailyAverage,
    "V1SummariesData": V1SummariesData,
    "V1SummariesEntry": V1SummariesEntry,
    "V1SummariesGrandTotal": V1SummariesGrandTotal,
    "V1SummariesRange": V1SummariesRange,
    "V1SummariesViewModel": V1SummariesViewModel,
    "V1User": V1User,
    "V1UserAgentEntry": V1UserAgentEntry,
    "V1UserAgentsViewModel": V1UserAgentsViewModel,
    "V1UserViewModel": V1UserViewModel,
}
# Values that can never hold a nested model, so they need no cycle bookkeeping.
_SCALARS = (str, bytes, bool, int, float)


def _as_mapping(value: object) -> Mapping[str, object]:
    if isinstance(value, Mapping):
        return value
    if is_dataclass(value) and not isinstance(value, type):
        return {field.name: getattr(value, field.name) for field in fields(value)}
    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        return model_dump(by_alias=True, exclude_unset=True)
    raise TypeError("model construction values must be mappings or model instances")


def _field_value(value: object, wire_name: str, python_name: str) -> tuple[bool, object]:
    mapping = _as_mapping(value)
    if python_name in mapping:
        return True, mapping[python_name]
    if wire_name in mapping:
        return True, mapping[wire_name]
    return False, None


def _property_name(wire_name: str, schema: Mapping[str, Any]) -> str:
    return str(schema.get("python", wire_name))


def _child_field(field: str, child: str) -> str:
    return f"{field}.{child}" if field else child


def _resolve(schema: Mapping[str, Any]) -> tuple[str | None, Mapping[str, Any]]:
    """Follows a reference chain to the named schema it points at."""
    name: str | None = None
    visited: set[str] = set()
    reference = schema.get("ref")
    while isinstance(reference, str) and reference not in visited:
        visited.add(reference)
        name = reference
        target = _SCHEMAS.get(reference)
        schema = target if isinstance(target, Mapping) else {}
        reference = schema.get("ref")
    return name, schema


def _select_member(
    value: object,
    members: list[Any],
    field: str,
    active: set[tuple[int, int]],
) -> Mapping[str, Any] | None:
    """Returns the first union member the value satisfies, or raises its error."""
    rejection: SdkValidationError | None = None
    for member in members:
        if not isinstance(member, Mapping):
            continue
        try:
            _validate_node(value, member, field, active)
        except SdkValidationError as error:
            rejection = rejection or error
            continue
        return member
    if rejection is not None:
        raise rejection
    return None


def _validate_node(
    value: object,
    schema: Mapping[str, Any],
    field: str,
    active: set[tuple[int, int]],
) -> None:
    _name, resolved = _resolve(schema)
    if value is None:
        return

    # Recursive schemas describe finite values, so every node is validated. Only
    # a value that contains itself repeats a (value, schema) pair, and that can
    # never be constructed into a model.
    if not isinstance(value, _SCALARS):
        visit = (id(value), id(resolved))
        if visit in active:
            raise SdkValidationError(
                field,
                "recursion",
                f"Validation failed for '{field}': model value contains itself",
            )
        active = {*active, visit}

    for member in resolved.get("allOf", ()):
        if isinstance(member, Mapping):
            _validate_node(value, member, field, active)

    members = resolved.get("oneOf") or resolved.get("anyOf")
    if isinstance(members, list) and members:
        _select_member(value, members, field, active)
        return

    properties = resolved.get("properties")
    if isinstance(properties, Mapping):
        required = resolved.get("required", ())
        for wire_name in required if isinstance(required, list) else ():
            property_schema = properties.get(wire_name)
            python_name = (
                _property_name(wire_name, property_schema)
                if isinstance(property_schema, Mapping)
                else wire_name
            )
            present, property_value = _field_value(value, wire_name, python_name)
            if (
                not present
                or property_value is None
                and not (
                    isinstance(property_schema, Mapping) and property_schema.get("nullable") is True
                )
            ):
                raise SdkValidationError(
                    _child_field(field, wire_name),
                    "required",
                    f"Missing required property '{wire_name}'",
                )

        for wire_name, property_schema in properties.items():
            if not isinstance(property_schema, Mapping):
                continue
            present, property_value = _field_value(
                value, wire_name, _property_name(wire_name, property_schema)
            )
            if present:
                _validate_node(
                    property_value,
                    property_schema,
                    _child_field(field, wire_name),
                    active,
                )

    additional = resolved.get("additionalProperties")
    if isinstance(additional, Mapping) and isinstance(value, Mapping):
        known = {
            name
            for wire_name, property_schema in (properties or {}).items()
            if isinstance(property_schema, Mapping)
            for name in (wire_name, _property_name(wire_name, property_schema))
        }
        for key, property_value in value.items():
            if key not in known:
                _validate_node(property_value, additional, _child_field(field, key), active)

    items = resolved.get("items")
    if isinstance(value, (list, tuple)) and isinstance(items, Mapping):
        for index, item in enumerate(value):
            _validate_node(item, items, _child_field(field, str(index)), active)

    if resolved.get("format") == "date":
        validate_date(field, cast(str, value))


def _build(type_name: str | None, values: dict[str, object]) -> object:
    model_type = _MODEL_TYPES.get(type_name) if type_name is not None else None
    if model_type is None or MODEL_CONSTRUCTION_STYLE == "typeddict":
        return values
    return model_type(**values)


def _hydrate(value: object, schema: Mapping[str, Any], field: str) -> object:
    """Builds the public value for one schema node, constructing nested models."""
    name, resolved = _resolve(schema)
    if value is None:
        return None

    members = resolved.get("oneOf") or resolved.get("anyOf")
    if isinstance(members, list) and members:
        member = _select_member(value, members, field, set())
        return value if member is None else _hydrate(value, member, field)

    properties = resolved.get("properties")
    if isinstance(properties, Mapping):
        values: dict[str, object] = {}
        for wire_name, property_schema in properties.items():
            if not isinstance(property_schema, Mapping):
                continue
            python_name = _property_name(wire_name, property_schema)
            present, property_value = _field_value(value, wire_name, python_name)
            if present:
                values[python_name] = _hydrate(
                    property_value, property_schema, _child_field(field, wire_name)
                )
        return _build(name, values)

    additional = resolved.get("additionalProperties")
    if isinstance(additional, Mapping) and isinstance(value, Mapping):
        return {
            key: _hydrate(item, additional, _child_field(field, key)) for key, item in value.items()
        }

    items = resolved.get("items")
    if isinstance(items, Mapping) and isinstance(value, (list, tuple)):
        return [
            _hydrate(item, items, _child_field(field, str(index)))
            for index, item in enumerate(value)
        ]

    return value


def _construct_model(value: object, type_name: str) -> object:
    if type_name not in _MODEL_TYPES:
        raise ValueError(f"unknown model type: {type_name}")
    _validate_node(value, {"ref": type_name}, "", set())
    if MODEL_CONSTRUCTION_STYLE == "pydantic":
        # Pydantic owns nested construction: its declared field types already
        # describe every referenced model. The wire remapper first restores the
        # spec spelling that the generated aliases and validators expect.
        return _MODEL_TYPES[type_name].model_validate(to_wire(value, type_name))
    return _hydrate(value, {"ref": type_name}, "")


def create_models_diagnostics(value: Mapping[str, object]) -> ModelsDiagnostics:
    """Construct one ModelsDiagnostics after applying its schema constraints."""
    return cast(ModelsDiagnostics, _construct_model(value, "ModelsDiagnostics"))


def create_models_heartbeat(value: Mapping[str, object]) -> ModelsHeartbeat:
    """Construct one ModelsHeartbeat after applying its schema constraints."""
    return cast(ModelsHeartbeat, _construct_model(value, "ModelsHeartbeat"))


def create_models_summary(value: Mapping[str, object]) -> ModelsSummary:
    """Construct one ModelsSummary after applying its schema constraints."""
    return cast(ModelsSummary, _construct_model(value, "ModelsSummary"))


def create_models_summary_item(value: Mapping[str, object]) -> ModelsSummaryItem:
    """Construct one ModelsSummaryItem after applying its schema constraints."""
    return cast(ModelsSummaryItem, _construct_model(value, "ModelsSummaryItem"))


def create_v1_all_time_data(value: Mapping[str, object]) -> V1AllTimeData:
    """Construct one V1AllTimeData after applying its schema constraints."""
    return cast(V1AllTimeData, _construct_model(value, "V1AllTimeData"))


def create_v1_all_time_range(value: Mapping[str, object]) -> V1AllTimeRange:
    """Construct one V1AllTimeRange after applying its schema constraints."""
    return cast(V1AllTimeRange, _construct_model(value, "V1AllTimeRange"))


def create_v1_all_time_view_model(value: Mapping[str, object]) -> V1AllTimeViewModel:
    """Construct one V1AllTimeViewModel after applying its schema constraints."""
    return cast(V1AllTimeViewModel, _construct_model(value, "V1AllTimeViewModel"))


def create_v1_badge_data(value: Mapping[str, object]) -> V1BadgeData:
    """Construct one V1BadgeData after applying its schema constraints."""
    return cast(V1BadgeData, _construct_model(value, "V1BadgeData"))


def create_v1_heartbeat_entry(value: Mapping[str, object]) -> V1HeartbeatEntry:
    """Construct one V1HeartbeatEntry after applying its schema constraints."""
    return cast(V1HeartbeatEntry, _construct_model(value, "V1HeartbeatEntry"))


def create_v1_heartbeats_result(value: Mapping[str, object]) -> V1HeartbeatsResult:
    """Construct one V1HeartbeatsResult after applying its schema constraints."""
    return cast(V1HeartbeatsResult, _construct_model(value, "V1HeartbeatsResult"))


def create_v1_leaders_current_user(value: Mapping[str, object]) -> V1LeadersCurrentUser:
    """Construct one V1LeadersCurrentUser after applying its schema constraints."""
    return cast(V1LeadersCurrentUser, _construct_model(value, "V1LeadersCurrentUser"))


def create_v1_leaders_entry(value: Mapping[str, object]) -> V1LeadersEntry:
    """Construct one V1LeadersEntry after applying its schema constraints."""
    return cast(V1LeadersEntry, _construct_model(value, "V1LeadersEntry"))


def create_v1_leaders_language(value: Mapping[str, object]) -> V1LeadersLanguage:
    """Construct one V1LeadersLanguage after applying its schema constraints."""
    return cast(V1LeadersLanguage, _construct_model(value, "V1LeadersLanguage"))


def create_v1_leaders_range(value: Mapping[str, object]) -> V1LeadersRange:
    """Construct one V1LeadersRange after applying its schema constraints."""
    return cast(V1LeadersRange, _construct_model(value, "V1LeadersRange"))


def create_v1_leaders_running_total(value: Mapping[str, object]) -> V1LeadersRunningTotal:
    """Construct one V1LeadersRunningTotal after applying its schema constraints."""
    return cast(V1LeadersRunningTotal, _construct_model(value, "V1LeadersRunningTotal"))


def create_v1_leaders_view_model(value: Mapping[str, object]) -> V1LeadersViewModel:
    """Construct one V1LeadersViewModel after applying its schema constraints."""
    return cast(V1LeadersViewModel, _construct_model(value, "V1LeadersViewModel"))


def create_v1_project(value: Mapping[str, object]) -> V1Project:
    """Construct one V1Project after applying its schema constraints."""
    return cast(V1Project, _construct_model(value, "V1Project"))


def create_v1_project_view_model(value: Mapping[str, object]) -> V1ProjectViewModel:
    """Construct one V1ProjectViewModel after applying its schema constraints."""
    return cast(V1ProjectViewModel, _construct_model(value, "V1ProjectViewModel"))


def create_v1_projects_view_model(value: Mapping[str, object]) -> V1ProjectsViewModel:
    """Construct one V1ProjectsViewModel after applying its schema constraints."""
    return cast(V1ProjectsViewModel, _construct_model(value, "V1ProjectsViewModel"))


def create_v1_stats_data(value: Mapping[str, object]) -> V1StatsData:
    """Construct one V1StatsData after applying its schema constraints."""
    return cast(V1StatsData, _construct_model(value, "V1StatsData"))


def create_v1_stats_view_model(value: Mapping[str, object]) -> V1StatsViewModel:
    """Construct one V1StatsViewModel after applying its schema constraints."""
    return cast(V1StatsViewModel, _construct_model(value, "V1StatsViewModel"))


def create_v1_status_bar_view_model(value: Mapping[str, object]) -> V1StatusBarViewModel:
    """Construct one V1StatusBarViewModel after applying its schema constraints."""
    return cast(V1StatusBarViewModel, _construct_model(value, "V1StatusBarViewModel"))


def create_v1_summaries_cumulative_total(value: Mapping[str, object]) -> V1SummariesCumulativeTotal:
    """Construct one V1SummariesCumulativeTotal after applying its schema constraints."""
    return cast(V1SummariesCumulativeTotal, _construct_model(value, "V1SummariesCumulativeTotal"))


def create_v1_summaries_daily_average(value: Mapping[str, object]) -> V1SummariesDailyAverage:
    """Construct one V1SummariesDailyAverage after applying its schema constraints."""
    return cast(V1SummariesDailyAverage, _construct_model(value, "V1SummariesDailyAverage"))


def create_v1_summaries_data(value: Mapping[str, object]) -> V1SummariesData:
    """Construct one V1SummariesData after applying its schema constraints."""
    return cast(V1SummariesData, _construct_model(value, "V1SummariesData"))


def create_v1_summaries_entry(value: Mapping[str, object]) -> V1SummariesEntry:
    """Construct one V1SummariesEntry after applying its schema constraints."""
    return cast(V1SummariesEntry, _construct_model(value, "V1SummariesEntry"))


def create_v1_summaries_grand_total(value: Mapping[str, object]) -> V1SummariesGrandTotal:
    """Construct one V1SummariesGrandTotal after applying its schema constraints."""
    return cast(V1SummariesGrandTotal, _construct_model(value, "V1SummariesGrandTotal"))


def create_v1_summaries_range(value: Mapping[str, object]) -> V1SummariesRange:
    """Construct one V1SummariesRange after applying its schema constraints."""
    return cast(V1SummariesRange, _construct_model(value, "V1SummariesRange"))


def create_v1_summaries_view_model(value: Mapping[str, object]) -> V1SummariesViewModel:
    """Construct one V1SummariesViewModel after applying its schema constraints."""
    return cast(V1SummariesViewModel, _construct_model(value, "V1SummariesViewModel"))


def create_v1_user(value: Mapping[str, object]) -> V1User:
    """Construct one V1User after applying its schema constraints."""
    return cast(V1User, _construct_model(value, "V1User"))


def create_v1_user_agent_entry(value: Mapping[str, object]) -> V1UserAgentEntry:
    """Construct one V1UserAgentEntry after applying its schema constraints."""
    return cast(V1UserAgentEntry, _construct_model(value, "V1UserAgentEntry"))


def create_v1_user_agents_view_model(value: Mapping[str, object]) -> V1UserAgentsViewModel:
    """Construct one V1UserAgentsViewModel after applying its schema constraints."""
    return cast(V1UserAgentsViewModel, _construct_model(value, "V1UserAgentsViewModel"))


def create_v1_user_view_model(value: Mapping[str, object]) -> V1UserViewModel:
    """Construct one V1UserViewModel after applying its schema constraints."""
    return cast(V1UserViewModel, _construct_model(value, "V1UserViewModel"))


def serialize_model(value: object, type_name: str) -> object:
    """Serialize a constructed model using the generated wire-name registry."""
    if type_name not in _MODEL_TYPES:
        raise ValueError(f"unknown model type: {type_name}")
    return to_wire(value, type_name)


def deserialize_model(value: object, type_name: str) -> object:
    """Validate and construct a model from its JSON-shaped representation."""
    return _construct_model(value, type_name)


__all__ = [
    "MODEL_CONSTRUCTION_STYLE",
    "create_models_diagnostics",
    "create_models_heartbeat",
    "create_models_summary",
    "create_models_summary_item",
    "create_v1_all_time_data",
    "create_v1_all_time_range",
    "create_v1_all_time_view_model",
    "create_v1_badge_data",
    "create_v1_heartbeat_entry",
    "create_v1_heartbeats_result",
    "create_v1_leaders_current_user",
    "create_v1_leaders_entry",
    "create_v1_leaders_language",
    "create_v1_leaders_range",
    "create_v1_leaders_running_total",
    "create_v1_leaders_view_model",
    "create_v1_project",
    "create_v1_project_view_model",
    "create_v1_projects_view_model",
    "create_v1_stats_data",
    "create_v1_stats_view_model",
    "create_v1_status_bar_view_model",
    "create_v1_summaries_cumulative_total",
    "create_v1_summaries_daily_average",
    "create_v1_summaries_data",
    "create_v1_summaries_entry",
    "create_v1_summaries_grand_total",
    "create_v1_summaries_range",
    "create_v1_summaries_view_model",
    "create_v1_user",
    "create_v1_user_agent_entry",
    "create_v1_user_agents_view_model",
    "create_v1_user_view_model",
    "deserialize_model",
    "serialize_model",
]
