# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
import re
from collections.abc import Mapping, Sequence
from urllib.parse import urlparse

from ._client_config import _wire_scalar
from .errors import SdkValidationError


def validate_required(
    value, required: Sequence[str], field_names: Mapping[str, str] | None = None
) -> None:
    if not isinstance(value, dict):
        return
    for field in required:
        # A renamed field may arrive under its Python name instead of the wire key.
        if field not in value and (field_names or {}).get(field) not in value:
            raise SdkValidationError(field, "required", f"Missing required property '{field}'")


def validate_enum(field: str, value, allowed: Sequence) -> None:
    if value not in allowed:
        raise SdkValidationError(
            field,
            "enum",
            f"Validation failed for '{field}': must be one of {', '.join(map(str, allowed))}",
            {"allowed": list(allowed)},
        )


def validate_range(
    field: str,
    value,
    *,
    min: float | None = None,
    max: float | None = None,
    exclusive_min: float | None = None,
    exclusive_max: float | None = None,
    multiple_of: float | None = None,
) -> None:
    if min is not None and value < min:
        raise SdkValidationError(
            field, "range", f"Validation failed for '{field}': must be >= {min}", {"min": min}
        )
    if max is not None and value > max:
        raise SdkValidationError(
            field, "range", f"Validation failed for '{field}': must be <= {max}", {"max": max}
        )
    if exclusive_min is not None and value <= exclusive_min:
        raise SdkValidationError(
            field,
            "range",
            f"Validation failed for '{field}': must be > {exclusive_min}",
            {"min": exclusive_min, "exclusive": {"min": True}},
        )
    if exclusive_max is not None and value >= exclusive_max:
        raise SdkValidationError(
            field,
            "range",
            f"Validation failed for '{field}': must be < {exclusive_max}",
            {"max": exclusive_max, "exclusive": {"max": True}},
        )
    if multiple_of is not None and multiple_of != 0 and value % multiple_of != 0:
        raise SdkValidationError(
            field, "range", f"Validation failed for '{field}': must be a multiple of {multiple_of}"
        )


def validate_length(
    field: str, value: str | datetime.date, *, min: int | None = None, max: int | None = None
) -> None:
    wire_value = _wire_scalar(value)
    if min is not None and len(wire_value) < min:
        raise SdkValidationError(
            field,
            "length",
            f"Validation failed for '{field}': length must be >= {min}",
            {"min": min},
        )
    if max is not None and len(wire_value) > max:
        raise SdkValidationError(
            field,
            "length",
            f"Validation failed for '{field}': length must be <= {max}",
            {"max": max},
        )


def validate_items(field: str, value, *, min: int | None = None, max: int | None = None) -> None:
    if min is not None and len(value) < min:
        raise SdkValidationError(
            field,
            "items",
            f"Validation failed for '{field}': must have at least {min} items",
            {"min": min},
        )
    if max is not None and len(value) > max:
        raise SdkValidationError(
            field,
            "items",
            f"Validation failed for '{field}': must have at most {max} items",
            {"max": max},
        )


def validate_pattern(field: str, value: str | datetime.date, pattern: str) -> None:
    if re.search(pattern, _wire_scalar(value)) is None:
        raise SdkValidationError(
            field,
            "pattern",
            f"Validation failed for '{field}': must match pattern {pattern}",
            {"pattern": pattern},
        )


_EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


def validate_email(field: str, value: str) -> None:
    if not _EMAIL_RE.match(value):
        raise SdkValidationError(
            field, "format:email", f"Validation failed for '{field}': must be a valid email address"
        )


def validate_uri(field: str, value: str) -> None:
    parsed = urlparse(value)
    if not (parsed.scheme and parsed.netloc):
        raise SdkValidationError(
            field, "format:uri", f"Validation failed for '{field}': must be a valid URI"
        )


_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", re.IGNORECASE
)


def validate_uuid(field: str, value: str) -> None:
    if not _UUID_RE.match(value):
        raise SdkValidationError(
            field, "format:uuid", f"Validation failed for '{field}': must be a valid UUID"
        )


_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def validate_date(field: str, value: str | datetime.date) -> None:
    if isinstance(value, datetime.datetime):
        raise SdkValidationError(
            field,
            "format:date",
            f"Validation failed for '{field}': must be a valid date (YYYY-MM-DD)",
        )
    wire_value = _wire_scalar(value)
    if not _DATE_RE.match(wire_value):
        raise SdkValidationError(
            field,
            "format:date",
            f"Validation failed for '{field}': must be a valid date (YYYY-MM-DD)",
        )
    try:
        datetime.date.fromisoformat(wire_value)
    except ValueError as exc:
        raise SdkValidationError(
            field,
            "format:date",
            f"Validation failed for '{field}': must be a valid date (YYYY-MM-DD)",
        ) from exc


_DATE_TIME_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$")


def validate_date_time(field: str, value: str | datetime.datetime) -> None:
    wire_value = _wire_scalar(value)
    if not _DATE_TIME_RE.match(wire_value):
        raise SdkValidationError(
            field,
            "format:date-time",
            f"Validation failed for '{field}': must be a valid ISO 8601 date-time",
        )
    try:
        parsed = datetime.datetime.fromisoformat(
            f"{wire_value[:-1]}+00:00" if wire_value.endswith("Z") else wire_value
        )
    except ValueError as exc:
        raise SdkValidationError(
            field,
            "format:date-time",
            f"Validation failed for '{field}': must be a valid ISO 8601 date-time",
        ) from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise SdkValidationError(
            field,
            "format:date-time",
            f"Validation failed for '{field}': must be a valid ISO 8601 date-time",
        )
