# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from dataclasses import fields, is_dataclass
from enum import Enum
from typing import Any

from ._client_config import NOT_GIVEN, _wire_scalar
from .errors import SdkValidationError

_MISSING = object()


_WIRE_SCHEMAS: dict[str, tuple[Any, dict[str, tuple[str, str | None]]]] = {
    "ModelsDiagnostics": (
        None,
        {
            "architecture": ("architecture", None),
            "cli_version": ("cli_version", None),
            "id": ("id", None),
            "logs": ("logs", None),
            "platform": ("platform", None),
            "plugin": ("plugin", None),
            "stacktrace": ("stacktrace", None),
        },
    ),
    "ModelsHeartbeat": (
        None,
        {
            "ai_input_tokens": ("ai_input_tokens", None),
            "ai_line_changes": ("ai_line_changes", None),
            "ai_output_tokens": ("ai_output_tokens", None),
            "ai_prompt_length": ("ai_prompt_length", None),
            "ai_session": ("ai_session", None),
            "branch": ("branch", None),
            "category": ("category", None),
            "created_at": ("created_at", None),
            "cursorpos": ("cursorpos", None),
            "editor": ("editor", None),
            "entity": ("entity", None),
            "human_line_changes": ("human_line_changes", None),
            "is_write": ("is_write", None),
            "language": ("language", None),
            "line_additions": ("line_additions", None),
            "line_deletions": ("line_deletions", None),
            "lineno": ("lineno", None),
            "lines": ("lines", None),
            "machine": ("machine", None),
            "operating_system": ("operating_system", None),
            "project": ("project", None),
            "project_root_count": ("project_root_count", None),
            "time": ("time", None),
            "type": ("type", None),
            "user_agent": ("user_agent", None),
        },
    ),
    "ModelsSummary": (
        None,
        {
            "branches": ("branches", "ModelsSummaryItem"),
            "categories": ("categories", "ModelsSummaryItem"),
            "editors": ("editors", "ModelsSummaryItem"),
            "entities": ("entities", "ModelsSummaryItem"),
            "from_": ("from", None),
            "labels": ("labels", "ModelsSummaryItem"),
            "languages": ("languages", "ModelsSummaryItem"),
            "machines": ("machines", "ModelsSummaryItem"),
            "operating_systems": ("operating_systems", "ModelsSummaryItem"),
            "projects": ("projects", "ModelsSummaryItem"),
            "to": ("to", None),
            "user_id": ("user_id", None),
        },
    ),
    "ModelsSummaryItem": (
        None,
        {
            "key": ("key", None),
            "total": ("total", None),
        },
    ),
    "V1AllTimeData": (
        None,
        {
            "is_up_to_date": ("is_up_to_date", None),
            "range": ("range", "V1AllTimeRange"),
            "text": ("text", None),
            "total_seconds": ("total_seconds", None),
        },
    ),
    "V1AllTimeRange": (
        None,
        {
            "end": ("end", None),
            "end_date": ("end_date", None),
            "start": ("start", None),
            "start_date": ("start_date", None),
            "timezone": ("timezone", None),
        },
    ),
    "V1AllTimeViewModel": (
        None,
        {
            "data": ("data", "V1AllTimeData"),
        },
    ),
    "V1BadgeData": (
        None,
        {
            "color": ("color", None),
            "label": ("label", None),
            "message": ("message", None),
            "schema_version": ("schemaVersion", None),
        },
    ),
    "V1HeartbeatEntry": (
        None,
        {
            "ai_input_tokens": ("ai_input_tokens", None),
            "ai_line_changes": ("ai_line_changes", None),
            "ai_output_tokens": ("ai_output_tokens", None),
            "ai_prompt_length": ("ai_prompt_length", None),
            "ai_session": ("ai_session", None),
            "branch": ("branch", None),
            "category": ("category", None),
            "created_at": ("created_at", None),
            "cursorpos": ("cursorpos", None),
            "entity": ("entity", None),
            "human_line_changes": ("human_line_changes", None),
            "id": ("id", None),
            "is_write": ("is_write", None),
            "language": ("language", None),
            "line_additions": ("line_additions", None),
            "line_deletions": ("line_deletions", None),
            "lineno": ("lineno", None),
            "lines": ("lines", None),
            "machine_name_id": ("machine_name_id", None),
            "project": ("project", None),
            "time": ("time", None),
            "type": ("type", None),
            "user_agent_id": ("user_agent_id", None),
            "user_id": ("user_id", None),
        },
    ),
    "V1HeartbeatsResult": (
        None,
        {
            "data": ("data", "V1HeartbeatEntry"),
            "end": ("end", None),
            "start": ("start", None),
            "timezone": ("timezone", None),
        },
    ),
    "V1LeadersCurrentUser": (
        None,
        {
            "page": ("page", None),
            "rank": ("rank", None),
            "user": ("user", "V1User"),
        },
    ),
    "V1LeadersEntry": (
        None,
        {
            "rank": ("rank", None),
            "running_total": ("running_total", "V1LeadersRunningTotal"),
            "user": ("user", "V1User"),
        },
    ),
    "V1LeadersLanguage": (
        None,
        {
            "name": ("name", None),
            "total_seconds": ("total_seconds", None),
        },
    ),
    "V1LeadersRange": (
        None,
        {
            "end_date": ("end_date", None),
            "end_text": ("end_text", None),
            "name": ("name", None),
            "start_date": ("start_date", None),
            "start_text": ("start_text", None),
            "text": ("text", None),
        },
    ),
    "V1LeadersRunningTotal": (
        None,
        {
            "daily_average": ("daily_average", None),
            "human_readable_daily_average": ("human_readable_daily_average", None),
            "human_readable_total": ("human_readable_total", None),
            "languages": ("languages", "V1LeadersLanguage"),
            "total_seconds": ("total_seconds", None),
        },
    ),
    "V1LeadersViewModel": (
        None,
        {
            "current_user": ("current_user", "V1LeadersCurrentUser"),
            "data": ("data", "V1LeadersEntry"),
            "language": ("language", None),
            "page": ("page", None),
            "range": ("range", "V1LeadersRange"),
            "total_pages": ("total_pages", None),
        },
    ),
    "V1Project": (
        None,
        {
            "created_at": ("created_at", None),
            "human_readable_last_heartbeat_at": ("human_readable_last_heartbeat_at", None),
            "id": ("id", None),
            "last_heartbeat_at": ("last_heartbeat_at", None),
            "name": ("name", None),
            "urlencoded_name": ("urlencoded_name", None),
        },
    ),
    "V1ProjectViewModel": (
        None,
        {
            "data": ("data", "V1Project"),
        },
    ),
    "V1ProjectsViewModel": (
        None,
        {
            "data": ("data", "V1Project"),
        },
    ),
    "V1StatsData": (
        None,
        {
            "branches": ("branches", "V1SummariesEntry"),
            "categories": ("categories", "V1SummariesEntry"),
            "daily_average": ("daily_average", None),
            "days_including_holidays": ("days_including_holidays", None),
            "editors": ("editors", "V1SummariesEntry"),
            "end": ("end", None),
            "human_readable_daily_average": ("human_readable_daily_average", None),
            "human_readable_range": ("human_readable_range", None),
            "human_readable_total": ("human_readable_total", None),
            "is_coding_activity_visible": ("is_coding_activity_visible", None),
            "is_other_usage_visible": ("is_other_usage_visible", None),
            "languages": ("languages", "V1SummariesEntry"),
            "machines": ("machines", "V1SummariesEntry"),
            "operating_systems": ("operating_systems", "V1SummariesEntry"),
            "projects": ("projects", "V1SummariesEntry"),
            "range": ("range", None),
            "start": ("start", None),
            "status": ("status", None),
            "timezone": ("timezone", None),
            "total_seconds": ("total_seconds", None),
            "user_id": ("user_id", None),
            "username": ("username", None),
        },
    ),
    "V1StatsViewModel": (
        None,
        {
            "data": ("data", "V1StatsData"),
        },
    ),
    "V1StatusBarViewModel": (
        None,
        {
            "cached_at": ("cached_at", None),
            "data": ("data", "V1SummariesData"),
        },
    ),
    "V1SummariesCumulativeTotal": (
        None,
        {
            "decimal": ("decimal", None),
            "digital": ("digital", None),
            "seconds": ("seconds", None),
            "text": ("text", None),
        },
    ),
    "V1SummariesDailyAverage": (
        None,
        {
            "days_including_holidays": ("days_including_holidays", None),
            "days_minus_holidays": ("days_minus_holidays", None),
            "holidays": ("holidays", None),
            "seconds": ("seconds", None),
            "seconds_including_other_language": ("seconds_including_other_language", None),
            "text": ("text", None),
            "text_including_other_language": ("text_including_other_language", None),
        },
    ),
    "V1SummariesData": (
        None,
        {
            "branches": ("branches", "V1SummariesEntry"),
            "categories": ("categories", "V1SummariesEntry"),
            "dependencies": ("dependencies", "V1SummariesEntry"),
            "editors": ("editors", "V1SummariesEntry"),
            "entities": ("entities", "V1SummariesEntry"),
            "grand_total": ("grand_total", "V1SummariesGrandTotal"),
            "languages": ("languages", "V1SummariesEntry"),
            "machines": ("machines", "V1SummariesEntry"),
            "operating_systems": ("operating_systems", "V1SummariesEntry"),
            "projects": ("projects", "V1SummariesEntry"),
            "range": ("range", "V1SummariesRange"),
        },
    ),
    "V1SummariesEntry": (
        None,
        {
            "digital": ("digital", None),
            "hours": ("hours", None),
            "minutes": ("minutes", None),
            "name": ("name", None),
            "percent": ("percent", None),
            "seconds": ("seconds", None),
            "text": ("text", None),
            "total_seconds": ("total_seconds", None),
        },
    ),
    "V1SummariesGrandTotal": (
        None,
        {
            "digital": ("digital", None),
            "hours": ("hours", None),
            "minutes": ("minutes", None),
            "text": ("text", None),
            "total_seconds": ("total_seconds", None),
        },
    ),
    "V1SummariesRange": (
        None,
        {
            "date": ("date", None),
            "end": ("end", None),
            "start": ("start", None),
            "text": ("text", None),
            "timezone": ("timezone", None),
        },
    ),
    "V1SummariesViewModel": (
        None,
        {
            "cumulative_total": ("cumulative_total", "V1SummariesCumulativeTotal"),
            "daily_average": ("daily_average", "V1SummariesDailyAverage"),
            "data": ("data", "V1SummariesData"),
            "end": ("end", None),
            "start": ("start", None),
        },
    ),
    "V1User": (
        None,
        {
            "created_at": ("created_at", None),
            "display_name": ("display_name", None),
            "email": ("email", None),
            "full_name": ("full_name", None),
            "id": ("id", None),
            "is_email_confirmed": ("is_email_confirmed", None),
            "is_email_public": ("is_email_public", None),
            "last_heartbeat_at": ("last_heartbeat_at", None),
            "last_plugin_name": ("last_plugin_name", None),
            "last_project": ("last_project", None),
            "modified_at": ("modified_at", None),
            "photo": ("photo", None),
            "timezone": ("timezone", None),
            "username": ("username", None),
            "website": ("website", None),
        },
    ),
    "V1UserAgentEntry": (
        None,
        {
            "editor": ("editor", None),
            "first_seen": ("first_seen", None),
            "id": ("id", None),
            "is_browser_extension": ("is_browser_extension", None),
            "is_desktop_app": ("is_desktop_app", None),
            "last_seen": ("last_seen", None),
            "os": ("os", None),
            "value": ("value", None),
            "version": ("version", None),
        },
    ),
    "V1UserAgentsViewModel": (
        None,
        {
            "data": ("data", "V1UserAgentEntry"),
            "total_pages": ("total_pages", None),
        },
    ),
    "V1UserViewModel": (
        None,
        {
            "data": ("data", "V1User"),
        },
    ),
}


_RESPONSE_ENUM_SCHEMAS: dict[str, object] = {}


def _response_field(field: str, child: str) -> str:
    return f"{field}.{child}" if field else child


def _response_index(field: str, index: int) -> str:
    return f"{field}[{index}]"


def _enum_matches(value: object, candidate: object) -> bool:
    if isinstance(value, bool) or isinstance(candidate, bool):
        return type(value) is type(candidate) and value == candidate
    if isinstance(value, (int, float)) and isinstance(candidate, (int, float)):
        return value == candidate
    return type(value) is type(candidate) and value == candidate


def _validate_response_enum_node(
    value: object,
    schema: object,
    field: str,
    active: set[tuple[int, int]],
) -> None:
    if not isinstance(schema, dict) or value is None:
        return
    reference = schema.get("ref")
    if isinstance(reference, str):
        target = _RESPONSE_ENUM_SCHEMAS.get(reference)
        if target is not None:
            _validate_response_enum_node(value, target, field, active)
        return

    visit = (id(value), id(schema))
    if visit in active:
        return
    active = {*active, visit}

    for member in schema.get("allOf", ()):
        _validate_response_enum_node(value, member, field, active)

    union = schema.get("oneOf") or schema.get("anyOf")
    if isinstance(union, list) and union:
        rejection: SdkValidationError | None = None
        for member in union:
            try:
                _validate_response_enum_node(value, member, field, active)
            except SdkValidationError as error:
                rejection = rejection or error
            else:
                return
        if rejection is not None:
            raise rejection

    properties = schema.get("properties")
    if isinstance(value, dict) and isinstance(properties, dict):
        for name, child_schema in properties.items():
            if name in value:
                _validate_response_enum_node(
                    value[name], child_schema, _response_field(field, name), active
                )

    additional = schema.get("additionalProperties")
    if isinstance(value, dict) and additional is not None:
        known = set(properties) if isinstance(properties, dict) else set()
        for name, child in value.items():
            if name not in known:
                _validate_response_enum_node(
                    child, additional, _response_field(field, name), active
                )

    items = schema.get("items")
    if isinstance(value, list) and items is not None:
        for index, child in enumerate(value):
            _validate_response_enum_node(child, items, _response_index(field, index), active)

    allowed = schema.get("enum")
    if isinstance(allowed, list) and not any(
        _enum_matches(value, candidate) for candidate in allowed
    ):
        raise SdkValidationError(
            field,
            "enum",
            f"Validation failed for '{field}': must be one of {allowed}",
            {"allowed": allowed},
        )


def _validate_response_enums(value: object, type_name: str) -> object:
    """Validates strict response enums against raw wire-shaped payload data."""
    schema = _RESPONSE_ENUM_SCHEMAS.get(type_name)
    if schema is not None:
        _validate_response_enum_node(value, schema, "", set())
    return value


def _plain_to_wire(value: Any) -> Any:
    if value is NOT_GIVEN:
        return NOT_GIVEN
    if isinstance(value, (datetime.datetime, datetime.date, datetime.time)):
        return _wire_scalar(value)
    if isinstance(value, Enum):
        return value.value
    if is_dataclass(value) and not isinstance(value, type):
        model_name = type(value).__name__
        if model_name in _WIRE_SCHEMAS:
            return to_wire(value, model_name)
        return {
            field.name: _plain_to_wire(getattr(value, field.name))
            for field in fields(value)
            if getattr(value, field.name) is not NOT_GIVEN
        }
    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        return _plain_to_wire(model_dump(by_alias=True, exclude_unset=True))
    if isinstance(value, dict):
        return {key: _plain_to_wire(item) for key, item in value.items() if item is not NOT_GIVEN}
    if isinstance(value, (list, tuple)):
        return [_plain_to_wire(item) for item in value]
    return value


def _to_wire_nested(value: Any, nested: str | None) -> Any:
    if nested is None:
        return _plain_to_wire(value)
    if isinstance(value, (list, tuple)):
        return [_to_wire_nested(item, nested) for item in value]
    if nested.startswith("map:"):
        value_type = nested[4:]
        return {key: _to_wire_nested(item, value_type) for key, item in value.items()}
    if nested.startswith("union:"):
        members = nested[6:].split("|")
        for member in members:
            cls = _WIRE_SCHEMAS[member][0]
            if cls is not None and isinstance(value, cls):
                return to_wire(value, member)
        if isinstance(value, dict):
            value_keys = set(value)
            member = max(
                members,
                key=lambda name: len(
                    value_keys
                    & (
                        set(_WIRE_SCHEMAS[name][1])
                        | {wire for wire, _nested in _WIRE_SCHEMAS[name][1].values()}
                    )
                ),
            )
            return to_wire(value, member)
        return _plain_to_wire(value)
    return to_wire(value, nested)


def to_wire(value: Any, type_name: str) -> Any:
    """Rewrites a payload's keys from idiomatic names to the spec's wire names,
    recursing into nested models and lists."""
    entry = _WIRE_SCHEMAS.get(type_name)
    if value is None or entry is None:
        return _plain_to_wire(value)
    if isinstance(value, list):
        return [to_wire(item, type_name) for item in value]
    _cls, schema = entry
    out: dict[str, Any] = {}
    for attr, (wire, nested) in schema.items():
        if isinstance(value, dict):
            # Accept values keyed by the idiomatic name or already by the wire
            # name, so callers may pass model instances or wire-shaped dicts.
            raw = value[attr] if attr in value else value.get(wire, _MISSING)
        else:
            raw = getattr(value, attr, _MISSING)
        if raw is _MISSING or raw is NOT_GIVEN:
            continue
        out[wire] = _to_wire_nested(raw, nested)
    return out
