# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from ._part001 import (
    get_heartbeats,
    get_heartbeats_sync,
    post_heartbeat3,
    post_heartbeat3_sync,
    post_heartbeat7,
    post_heartbeat7_sync,
)
from ._part002 import (
    post_heartbeat,
    post_heartbeat_sync,
    post_heartbeat4,
    post_heartbeat4_sync,
    post_heartbeat5,
    post_heartbeat5_sync,
)
from ._part003 import (
    post_heartbeat2,
    post_heartbeat2_sync,
    post_heartbeat6,
    post_heartbeat6_sync,
    post_heartbeat8,
    post_heartbeat8_sync,
)

__all__ = [
    "get_heartbeats",
    "get_heartbeats_sync",
    "post_heartbeat",
    "post_heartbeat2",
    "post_heartbeat2_sync",
    "post_heartbeat3",
    "post_heartbeat3_sync",
    "post_heartbeat4",
    "post_heartbeat4_sync",
    "post_heartbeat5",
    "post_heartbeat5_sync",
    "post_heartbeat6",
    "post_heartbeat6_sync",
    "post_heartbeat7",
    "post_heartbeat7_sync",
    "post_heartbeat8",
    "post_heartbeat8_sync",
    "post_heartbeat_sync",
]
