# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from wakapi_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from wakapi_unofficial_sdk.types import ModelsHeartbeat
from wakapi_unofficial_sdk.wire import to_wire


async def post_heartbeat(
    _client_config: ClientConfig,
    ai_input_tokens: int | NotGiven = NOT_GIVEN,
    ai_line_changes: int | NotGiven = NOT_GIVEN,
    ai_output_tokens: int | NotGiven = NOT_GIVEN,
    ai_prompt_length: int | NotGiven = NOT_GIVEN,
    ai_session: str | NotGiven = NOT_GIVEN,
    branch: str | NotGiven = NOT_GIVEN,
    category: str | NotGiven = NOT_GIVEN,
    created_at: float | NotGiven = NOT_GIVEN,
    cursorpos: int | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    entity: str | NotGiven = NOT_GIVEN,
    human_line_changes: int | NotGiven = NOT_GIVEN,
    is_write: bool | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    line_additions: int | NotGiven = NOT_GIVEN,
    line_deletions: int | NotGiven = NOT_GIVEN,
    lineno: int | NotGiven = NOT_GIVEN,
    lines: int | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    project_root_count: int | NotGiven = NOT_GIVEN,
    time: float | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    user_agent: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits a single heartbeat containing activity data. Send the heartbeat as a JSON
    object, using fields such as `entity`, `category`, and `language` to describe the
    recorded activity.

    Args:
        ai_input_tokens: Optional `integer` value serialized in the `ai_input_tokens` wire field.
        ai_line_changes: Optional `integer` value serialized in the `ai_line_changes` wire field.
        ai_output_tokens: Optional `integer` value serialized in the `ai_output_tokens` wire field.
        ai_prompt_length: Optional `integer` value serialized in the `ai_prompt_length` wire field.
        ai_session: Optional `string` value serialized in the `ai_session` wire field.
        branch: Optional `string` value serialized in the `branch` wire field.
        category: Optional `string` value serialized in the `category` wire field.
        created_at: https://gorm.io/docs/conventions.html#CreatedAt
        cursorpos: Optional `integer` value serialized in the `cursorpos` wire field.
        editor: ignored because editor might be parsed differently by wakatime
        entity: Optional `string` value serialized in the `entity` wire field.
        human_line_changes: Optional `integer` value serialized in the `human_line_changes` wire field.
        is_write: Optional `boolean` value serialized in the `is_write` wire field.
        language: Optional `string` value serialized in the `language` wire field.
        line_additions: Optional `integer` value serialized in the `line_additions` wire field.
        line_deletions: Optional `integer` value serialized in the `line_deletions` wire field.
        lineno: Optional `integer` value serialized in the `lineno` wire field.
        lines: Optional `integer` value serialized in the `lines` wire field.
        machine: ignored because wakatime api doesn't return machines currently
        operating_system: ignored because os might be parsed differently by wakatime
        project: Optional `string` value serialized in the `project` wire field.
        project_root_count: Optional `integer` value serialized in the `project_root_count` wire field.
        time: note: on sqlite, table will have an additional column `time_real`, introduced
            "manually" by migration 20260111 see https://github.com/muety/wakapi/issues/882
            for details
        type: Optional `string` value serialized in the `type` wire field.
        user_agent: Optional `string` value serialized in the `user_agent` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/heartbeat",
        json=omit_unset(
            {
                "ai_input_tokens": (
                    NOT_GIVEN if ai_input_tokens is NOT_GIVEN else to_wire(ai_input_tokens, "int")
                ),
                "ai_line_changes": (
                    NOT_GIVEN if ai_line_changes is NOT_GIVEN else to_wire(ai_line_changes, "int")
                ),
                "ai_output_tokens": (
                    NOT_GIVEN if ai_output_tokens is NOT_GIVEN else to_wire(ai_output_tokens, "int")
                ),
                "ai_prompt_length": (
                    NOT_GIVEN if ai_prompt_length is NOT_GIVEN else to_wire(ai_prompt_length, "int")
                ),
                "ai_session": (
                    NOT_GIVEN if ai_session is NOT_GIVEN else to_wire(ai_session, "str")
                ),
                "branch": (NOT_GIVEN if branch is NOT_GIVEN else to_wire(branch, "str")),
                "category": (NOT_GIVEN if category is NOT_GIVEN else to_wire(category, "str")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "float")
                ),
                "cursorpos": (NOT_GIVEN if cursorpos is NOT_GIVEN else to_wire(cursorpos, "int")),
                "editor": (NOT_GIVEN if editor is NOT_GIVEN else to_wire(editor, "str")),
                "entity": (NOT_GIVEN if entity is NOT_GIVEN else to_wire(entity, "str")),
                "human_line_changes": (
                    NOT_GIVEN
                    if human_line_changes is NOT_GIVEN
                    else to_wire(human_line_changes, "int")
                ),
                "is_write": (NOT_GIVEN if is_write is NOT_GIVEN else to_wire(is_write, "bool")),
                "language": (NOT_GIVEN if language is NOT_GIVEN else to_wire(language, "str")),
                "line_additions": (
                    NOT_GIVEN if line_additions is NOT_GIVEN else to_wire(line_additions, "int")
                ),
                "line_deletions": (
                    NOT_GIVEN if line_deletions is NOT_GIVEN else to_wire(line_deletions, "int")
                ),
                "lineno": (NOT_GIVEN if lineno is NOT_GIVEN else to_wire(lineno, "int")),
                "lines": (NOT_GIVEN if lines is NOT_GIVEN else to_wire(lines, "int")),
                "machine": (NOT_GIVEN if machine is NOT_GIVEN else to_wire(machine, "str")),
                "operating_system": (
                    NOT_GIVEN if operating_system is NOT_GIVEN else to_wire(operating_system, "str")
                ),
                "project": (NOT_GIVEN if project is NOT_GIVEN else to_wire(project, "str")),
                "project_root_count": (
                    NOT_GIVEN
                    if project_root_count is NOT_GIVEN
                    else to_wire(project_root_count, "int")
                ),
                "time": (NOT_GIVEN if time is NOT_GIVEN else to_wire(time, "float")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "user_agent": (
                    NOT_GIVEN if user_agent is NOT_GIVEN else to_wire(user_agent, "str")
                ),
            }
        ),
        operation_id="post_heartbeat",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def post_heartbeat_sync(
    _client_config: ClientConfig,
    ai_input_tokens: int | NotGiven = NOT_GIVEN,
    ai_line_changes: int | NotGiven = NOT_GIVEN,
    ai_output_tokens: int | NotGiven = NOT_GIVEN,
    ai_prompt_length: int | NotGiven = NOT_GIVEN,
    ai_session: str | NotGiven = NOT_GIVEN,
    branch: str | NotGiven = NOT_GIVEN,
    category: str | NotGiven = NOT_GIVEN,
    created_at: float | NotGiven = NOT_GIVEN,
    cursorpos: int | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    entity: str | NotGiven = NOT_GIVEN,
    human_line_changes: int | NotGiven = NOT_GIVEN,
    is_write: bool | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    line_additions: int | NotGiven = NOT_GIVEN,
    line_deletions: int | NotGiven = NOT_GIVEN,
    lineno: int | NotGiven = NOT_GIVEN,
    lines: int | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    project_root_count: int | NotGiven = NOT_GIVEN,
    time: float | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    user_agent: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits a single heartbeat containing activity data. Send the heartbeat as a JSON
    object, using fields such as `entity`, `category`, and `language` to describe the
    recorded activity.

    Args:
        ai_input_tokens: Optional `integer` value serialized in the `ai_input_tokens` wire field.
        ai_line_changes: Optional `integer` value serialized in the `ai_line_changes` wire field.
        ai_output_tokens: Optional `integer` value serialized in the `ai_output_tokens` wire field.
        ai_prompt_length: Optional `integer` value serialized in the `ai_prompt_length` wire field.
        ai_session: Optional `string` value serialized in the `ai_session` wire field.
        branch: Optional `string` value serialized in the `branch` wire field.
        category: Optional `string` value serialized in the `category` wire field.
        created_at: https://gorm.io/docs/conventions.html#CreatedAt
        cursorpos: Optional `integer` value serialized in the `cursorpos` wire field.
        editor: ignored because editor might be parsed differently by wakatime
        entity: Optional `string` value serialized in the `entity` wire field.
        human_line_changes: Optional `integer` value serialized in the `human_line_changes` wire field.
        is_write: Optional `boolean` value serialized in the `is_write` wire field.
        language: Optional `string` value serialized in the `language` wire field.
        line_additions: Optional `integer` value serialized in the `line_additions` wire field.
        line_deletions: Optional `integer` value serialized in the `line_deletions` wire field.
        lineno: Optional `integer` value serialized in the `lineno` wire field.
        lines: Optional `integer` value serialized in the `lines` wire field.
        machine: ignored because wakatime api doesn't return machines currently
        operating_system: ignored because os might be parsed differently by wakatime
        project: Optional `string` value serialized in the `project` wire field.
        project_root_count: Optional `integer` value serialized in the `project_root_count` wire field.
        time: note: on sqlite, table will have an additional column `time_real`, introduced
            "manually" by migration 20260111 see https://github.com/muety/wakapi/issues/882
            for details
        type: Optional `string` value serialized in the `type` wire field.
        user_agent: Optional `string` value serialized in the `user_agent` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/heartbeat",
        json=omit_unset(
            {
                "ai_input_tokens": (
                    NOT_GIVEN if ai_input_tokens is NOT_GIVEN else to_wire(ai_input_tokens, "int")
                ),
                "ai_line_changes": (
                    NOT_GIVEN if ai_line_changes is NOT_GIVEN else to_wire(ai_line_changes, "int")
                ),
                "ai_output_tokens": (
                    NOT_GIVEN if ai_output_tokens is NOT_GIVEN else to_wire(ai_output_tokens, "int")
                ),
                "ai_prompt_length": (
                    NOT_GIVEN if ai_prompt_length is NOT_GIVEN else to_wire(ai_prompt_length, "int")
                ),
                "ai_session": (
                    NOT_GIVEN if ai_session is NOT_GIVEN else to_wire(ai_session, "str")
                ),
                "branch": (NOT_GIVEN if branch is NOT_GIVEN else to_wire(branch, "str")),
                "category": (NOT_GIVEN if category is NOT_GIVEN else to_wire(category, "str")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "float")
                ),
                "cursorpos": (NOT_GIVEN if cursorpos is NOT_GIVEN else to_wire(cursorpos, "int")),
                "editor": (NOT_GIVEN if editor is NOT_GIVEN else to_wire(editor, "str")),
                "entity": (NOT_GIVEN if entity is NOT_GIVEN else to_wire(entity, "str")),
                "human_line_changes": (
                    NOT_GIVEN
                    if human_line_changes is NOT_GIVEN
                    else to_wire(human_line_changes, "int")
                ),
                "is_write": (NOT_GIVEN if is_write is NOT_GIVEN else to_wire(is_write, "bool")),
                "language": (NOT_GIVEN if language is NOT_GIVEN else to_wire(language, "str")),
                "line_additions": (
                    NOT_GIVEN if line_additions is NOT_GIVEN else to_wire(line_additions, "int")
                ),
                "line_deletions": (
                    NOT_GIVEN if line_deletions is NOT_GIVEN else to_wire(line_deletions, "int")
                ),
                "lineno": (NOT_GIVEN if lineno is NOT_GIVEN else to_wire(lineno, "int")),
                "lines": (NOT_GIVEN if lines is NOT_GIVEN else to_wire(lines, "int")),
                "machine": (NOT_GIVEN if machine is NOT_GIVEN else to_wire(machine, "str")),
                "operating_system": (
                    NOT_GIVEN if operating_system is NOT_GIVEN else to_wire(operating_system, "str")
                ),
                "project": (NOT_GIVEN if project is NOT_GIVEN else to_wire(project, "str")),
                "project_root_count": (
                    NOT_GIVEN
                    if project_root_count is NOT_GIVEN
                    else to_wire(project_root_count, "int")
                ),
                "time": (NOT_GIVEN if time is NOT_GIVEN else to_wire(time, "float")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "user_agent": (
                    NOT_GIVEN if user_agent is NOT_GIVEN else to_wire(user_agent, "str")
                ),
            }
        ),
        operation_id="post_heartbeat",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


async def post_heartbeat5(
    _client_config: ClientConfig,
    body: list[ModelsHeartbeat],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits multiple heartbeats in one request. Send a JSON array of heartbeat objects
    to record activity in bulk.
    """

    _resp = await sdk_request(
        "POST",
        "/heartbeats",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "ModelsHeartbeat")),
        operation_id="post_heartbeat5",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def post_heartbeat5_sync(
    _client_config: ClientConfig,
    body: list[ModelsHeartbeat],
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits multiple heartbeats in one request. Send a JSON array of heartbeat objects
    to record activity in bulk.
    """

    _resp = sdk_request_sync(
        "POST",
        "/heartbeats",
        json=(NOT_GIVEN if body is NOT_GIVEN else to_wire(body, "ModelsHeartbeat")),
        operation_id="post_heartbeat5",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


async def post_heartbeat4(
    _client_config: ClientConfig,
    user: str,
    ai_input_tokens: int | NotGiven = NOT_GIVEN,
    ai_line_changes: int | NotGiven = NOT_GIVEN,
    ai_output_tokens: int | NotGiven = NOT_GIVEN,
    ai_prompt_length: int | NotGiven = NOT_GIVEN,
    ai_session: str | NotGiven = NOT_GIVEN,
    branch: str | NotGiven = NOT_GIVEN,
    category: str | NotGiven = NOT_GIVEN,
    created_at: float | NotGiven = NOT_GIVEN,
    cursorpos: int | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    entity: str | NotGiven = NOT_GIVEN,
    human_line_changes: int | NotGiven = NOT_GIVEN,
    is_write: bool | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    line_additions: int | NotGiven = NOT_GIVEN,
    line_deletions: int | NotGiven = NOT_GIVEN,
    lineno: int | NotGiven = NOT_GIVEN,
    lines: int | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    project_root_count: int | NotGiven = NOT_GIVEN,
    time: float | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    user_agent: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits a single heartbeat for a specified user. Send the heartbeat as a JSON object
    containing activity data such as `entity`, `category`, and `language`.

    Args:
        user: Username (or current)
        ai_input_tokens: Optional `integer` value serialized in the `ai_input_tokens` wire field.
        ai_line_changes: Optional `integer` value serialized in the `ai_line_changes` wire field.
        ai_output_tokens: Optional `integer` value serialized in the `ai_output_tokens` wire field.
        ai_prompt_length: Optional `integer` value serialized in the `ai_prompt_length` wire field.
        ai_session: Optional `string` value serialized in the `ai_session` wire field.
        branch: Optional `string` value serialized in the `branch` wire field.
        category: Optional `string` value serialized in the `category` wire field.
        created_at: https://gorm.io/docs/conventions.html#CreatedAt
        cursorpos: Optional `integer` value serialized in the `cursorpos` wire field.
        editor: ignored because editor might be parsed differently by wakatime
        entity: Optional `string` value serialized in the `entity` wire field.
        human_line_changes: Optional `integer` value serialized in the `human_line_changes` wire field.
        is_write: Optional `boolean` value serialized in the `is_write` wire field.
        language: Optional `string` value serialized in the `language` wire field.
        line_additions: Optional `integer` value serialized in the `line_additions` wire field.
        line_deletions: Optional `integer` value serialized in the `line_deletions` wire field.
        lineno: Optional `integer` value serialized in the `lineno` wire field.
        lines: Optional `integer` value serialized in the `lines` wire field.
        machine: ignored because wakatime api doesn't return machines currently
        operating_system: ignored because os might be parsed differently by wakatime
        project: Optional `string` value serialized in the `project` wire field.
        project_root_count: Optional `integer` value serialized in the `project_root_count` wire field.
        time: note: on sqlite, table will have an additional column `time_real`, introduced
            "manually" by migration 20260111 see https://github.com/muety/wakapi/issues/882
            for details
        type: Optional `string` value serialized in the `type` wire field.
        user_agent: Optional `string` value serialized in the `user_agent` wire field.
    """

    _resp = await sdk_request(
        "POST",
        f"/users/{encode_path_segment(user)}/heartbeats",
        json=omit_unset(
            {
                "ai_input_tokens": (
                    NOT_GIVEN if ai_input_tokens is NOT_GIVEN else to_wire(ai_input_tokens, "int")
                ),
                "ai_line_changes": (
                    NOT_GIVEN if ai_line_changes is NOT_GIVEN else to_wire(ai_line_changes, "int")
                ),
                "ai_output_tokens": (
                    NOT_GIVEN if ai_output_tokens is NOT_GIVEN else to_wire(ai_output_tokens, "int")
                ),
                "ai_prompt_length": (
                    NOT_GIVEN if ai_prompt_length is NOT_GIVEN else to_wire(ai_prompt_length, "int")
                ),
                "ai_session": (
                    NOT_GIVEN if ai_session is NOT_GIVEN else to_wire(ai_session, "str")
                ),
                "branch": (NOT_GIVEN if branch is NOT_GIVEN else to_wire(branch, "str")),
                "category": (NOT_GIVEN if category is NOT_GIVEN else to_wire(category, "str")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "float")
                ),
                "cursorpos": (NOT_GIVEN if cursorpos is NOT_GIVEN else to_wire(cursorpos, "int")),
                "editor": (NOT_GIVEN if editor is NOT_GIVEN else to_wire(editor, "str")),
                "entity": (NOT_GIVEN if entity is NOT_GIVEN else to_wire(entity, "str")),
                "human_line_changes": (
                    NOT_GIVEN
                    if human_line_changes is NOT_GIVEN
                    else to_wire(human_line_changes, "int")
                ),
                "is_write": (NOT_GIVEN if is_write is NOT_GIVEN else to_wire(is_write, "bool")),
                "language": (NOT_GIVEN if language is NOT_GIVEN else to_wire(language, "str")),
                "line_additions": (
                    NOT_GIVEN if line_additions is NOT_GIVEN else to_wire(line_additions, "int")
                ),
                "line_deletions": (
                    NOT_GIVEN if line_deletions is NOT_GIVEN else to_wire(line_deletions, "int")
                ),
                "lineno": (NOT_GIVEN if lineno is NOT_GIVEN else to_wire(lineno, "int")),
                "lines": (NOT_GIVEN if lines is NOT_GIVEN else to_wire(lines, "int")),
                "machine": (NOT_GIVEN if machine is NOT_GIVEN else to_wire(machine, "str")),
                "operating_system": (
                    NOT_GIVEN if operating_system is NOT_GIVEN else to_wire(operating_system, "str")
                ),
                "project": (NOT_GIVEN if project is NOT_GIVEN else to_wire(project, "str")),
                "project_root_count": (
                    NOT_GIVEN
                    if project_root_count is NOT_GIVEN
                    else to_wire(project_root_count, "int")
                ),
                "time": (NOT_GIVEN if time is NOT_GIVEN else to_wire(time, "float")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "user_agent": (
                    NOT_GIVEN if user_agent is NOT_GIVEN else to_wire(user_agent, "str")
                ),
            }
        ),
        operation_id="post_heartbeat4",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


def post_heartbeat4_sync(
    _client_config: ClientConfig,
    user: str,
    ai_input_tokens: int | NotGiven = NOT_GIVEN,
    ai_line_changes: int | NotGiven = NOT_GIVEN,
    ai_output_tokens: int | NotGiven = NOT_GIVEN,
    ai_prompt_length: int | NotGiven = NOT_GIVEN,
    ai_session: str | NotGiven = NOT_GIVEN,
    branch: str | NotGiven = NOT_GIVEN,
    category: str | NotGiven = NOT_GIVEN,
    created_at: float | NotGiven = NOT_GIVEN,
    cursorpos: int | NotGiven = NOT_GIVEN,
    editor: str | NotGiven = NOT_GIVEN,
    entity: str | NotGiven = NOT_GIVEN,
    human_line_changes: int | NotGiven = NOT_GIVEN,
    is_write: bool | NotGiven = NOT_GIVEN,
    language: str | NotGiven = NOT_GIVEN,
    line_additions: int | NotGiven = NOT_GIVEN,
    line_deletions: int | NotGiven = NOT_GIVEN,
    lineno: int | NotGiven = NOT_GIVEN,
    lines: int | NotGiven = NOT_GIVEN,
    machine: str | NotGiven = NOT_GIVEN,
    operating_system: str | NotGiven = NOT_GIVEN,
    project: str | NotGiven = NOT_GIVEN,
    project_root_count: int | NotGiven = NOT_GIVEN,
    time: float | NotGiven = NOT_GIVEN,
    type: str | NotGiven = NOT_GIVEN,
    user_agent: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> None:
    """Submits a single heartbeat for a specified user. Send the heartbeat as a JSON object
    containing activity data such as `entity`, `category`, and `language`.

    Args:
        user: Username (or current)
        ai_input_tokens: Optional `integer` value serialized in the `ai_input_tokens` wire field.
        ai_line_changes: Optional `integer` value serialized in the `ai_line_changes` wire field.
        ai_output_tokens: Optional `integer` value serialized in the `ai_output_tokens` wire field.
        ai_prompt_length: Optional `integer` value serialized in the `ai_prompt_length` wire field.
        ai_session: Optional `string` value serialized in the `ai_session` wire field.
        branch: Optional `string` value serialized in the `branch` wire field.
        category: Optional `string` value serialized in the `category` wire field.
        created_at: https://gorm.io/docs/conventions.html#CreatedAt
        cursorpos: Optional `integer` value serialized in the `cursorpos` wire field.
        editor: ignored because editor might be parsed differently by wakatime
        entity: Optional `string` value serialized in the `entity` wire field.
        human_line_changes: Optional `integer` value serialized in the `human_line_changes` wire field.
        is_write: Optional `boolean` value serialized in the `is_write` wire field.
        language: Optional `string` value serialized in the `language` wire field.
        line_additions: Optional `integer` value serialized in the `line_additions` wire field.
        line_deletions: Optional `integer` value serialized in the `line_deletions` wire field.
        lineno: Optional `integer` value serialized in the `lineno` wire field.
        lines: Optional `integer` value serialized in the `lines` wire field.
        machine: ignored because wakatime api doesn't return machines currently
        operating_system: ignored because os might be parsed differently by wakatime
        project: Optional `string` value serialized in the `project` wire field.
        project_root_count: Optional `integer` value serialized in the `project_root_count` wire field.
        time: note: on sqlite, table will have an additional column `time_real`, introduced
            "manually" by migration 20260111 see https://github.com/muety/wakapi/issues/882
            for details
        type: Optional `string` value serialized in the `type` wire field.
        user_agent: Optional `string` value serialized in the `user_agent` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/users/{encode_path_segment(user)}/heartbeats",
        json=omit_unset(
            {
                "ai_input_tokens": (
                    NOT_GIVEN if ai_input_tokens is NOT_GIVEN else to_wire(ai_input_tokens, "int")
                ),
                "ai_line_changes": (
                    NOT_GIVEN if ai_line_changes is NOT_GIVEN else to_wire(ai_line_changes, "int")
                ),
                "ai_output_tokens": (
                    NOT_GIVEN if ai_output_tokens is NOT_GIVEN else to_wire(ai_output_tokens, "int")
                ),
                "ai_prompt_length": (
                    NOT_GIVEN if ai_prompt_length is NOT_GIVEN else to_wire(ai_prompt_length, "int")
                ),
                "ai_session": (
                    NOT_GIVEN if ai_session is NOT_GIVEN else to_wire(ai_session, "str")
                ),
                "branch": (NOT_GIVEN if branch is NOT_GIVEN else to_wire(branch, "str")),
                "category": (NOT_GIVEN if category is NOT_GIVEN else to_wire(category, "str")),
                "created_at": (
                    NOT_GIVEN if created_at is NOT_GIVEN else to_wire(created_at, "float")
                ),
                "cursorpos": (NOT_GIVEN if cursorpos is NOT_GIVEN else to_wire(cursorpos, "int")),
                "editor": (NOT_GIVEN if editor is NOT_GIVEN else to_wire(editor, "str")),
                "entity": (NOT_GIVEN if entity is NOT_GIVEN else to_wire(entity, "str")),
                "human_line_changes": (
                    NOT_GIVEN
                    if human_line_changes is NOT_GIVEN
                    else to_wire(human_line_changes, "int")
                ),
                "is_write": (NOT_GIVEN if is_write is NOT_GIVEN else to_wire(is_write, "bool")),
                "language": (NOT_GIVEN if language is NOT_GIVEN else to_wire(language, "str")),
                "line_additions": (
                    NOT_GIVEN if line_additions is NOT_GIVEN else to_wire(line_additions, "int")
                ),
                "line_deletions": (
                    NOT_GIVEN if line_deletions is NOT_GIVEN else to_wire(line_deletions, "int")
                ),
                "lineno": (NOT_GIVEN if lineno is NOT_GIVEN else to_wire(lineno, "int")),
                "lines": (NOT_GIVEN if lines is NOT_GIVEN else to_wire(lines, "int")),
                "machine": (NOT_GIVEN if machine is NOT_GIVEN else to_wire(machine, "str")),
                "operating_system": (
                    NOT_GIVEN if operating_system is NOT_GIVEN else to_wire(operating_system, "str")
                ),
                "project": (NOT_GIVEN if project is NOT_GIVEN else to_wire(project, "str")),
                "project_root_count": (
                    NOT_GIVEN
                    if project_root_count is NOT_GIVEN
                    else to_wire(project_root_count, "int")
                ),
                "time": (NOT_GIVEN if time is NOT_GIVEN else to_wire(time, "float")),
                "type": (NOT_GIVEN if type is NOT_GIVEN else to_wire(type, "str")),
                "user_agent": (
                    NOT_GIVEN if user_agent is NOT_GIVEN else to_wire(user_agent, "str")
                ),
            }
        ),
        operation_id="post_heartbeat4",
        response_decoder="empty",
        request_options=request_options,
        config=_client_config,
    )


__all__ = [
    "post_heartbeat",
    "post_heartbeat4",
    "post_heartbeat4_sync",
    "post_heartbeat5",
    "post_heartbeat5_sync",
    "post_heartbeat_sync",
]
